services:
  api:
    image: unchained-local-go
    environment:
      - GOCACHE=/tmp
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.thorchain-v1-api.rule=Host(`api.thorchain-v1.localhost`)'
      - 'traefik.http.services.thorchain-v1-api.loadbalancer.server.port=3000'
    command: ["sh", "-c", "reflex -s -r '(pkg|internal|thorchain-v1)' -R 'swagger' -- sh -c 'swagger generate spec -w coinstacks/thorchain-v1 -o coinstacks/thorchain-v1/api/swagger.json -x protoc-gen-openapiv2 -m && go run cmd/thorchain-v1/main.go -env cmd/thorchain-v1/.env'"]
    working_dir: /app
    volumes:
      - ../..:/app
      - $GOPATH/pkg/mod/cache:/go/pkg/mod/cache
    networks:
      - thorchain-v1

networks:
  thorchain-v1:
    name: thorchain-v1_default
    external: true