// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "../../types";
import * as utilities from "../../utilities";

import {ObjectMeta} from "../../meta/v1";

/**
 * RabbitmqCluster is the Schema for the RabbitmqCluster API. Each instance of this object corresponds to a single RabbitMQ cluster.
 */
export class RabbitmqCluster extends pulumi.CustomResource {
    /**
     * Get an existing RabbitmqCluster resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): RabbitmqCluster {
        return new RabbitmqCluster(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'kubernetes:rabbitmq.com/v1beta1:RabbitmqCluster';

    /**
     * Returns true if the given object is an instance of RabbitmqCluster.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is RabbitmqCluster {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === RabbitmqCluster.__pulumiType;
    }

    public readonly apiVersion!: pulumi.Output<"rabbitmq.com/v1beta1" | undefined>;
    public readonly kind!: pulumi.Output<"RabbitmqCluster" | undefined>;
    public readonly metadata!: pulumi.Output<ObjectMeta | undefined>;
    /**
     * Spec is the desired state of the RabbitmqCluster Custom Resource.
     */
    public readonly spec!: pulumi.Output<outputs.rabbitmq.v1beta1.RabbitmqClusterSpec | undefined>;
    /**
     * Status presents the observed state of RabbitmqCluster
     */
    public readonly status!: pulumi.Output<outputs.rabbitmq.v1beta1.RabbitmqClusterStatus | undefined>;

    /**
     * Create a RabbitmqCluster resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: RabbitmqClusterArgs, opts?: pulumi.CustomResourceOptions) {
        let inputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            inputs["apiVersion"] = "rabbitmq.com/v1beta1";
            inputs["kind"] = "RabbitmqCluster";
            inputs["metadata"] = args ? args.metadata : undefined;
            inputs["spec"] = args ? args.spec : undefined;
            inputs["status"] = args ? args.status : undefined;
        } else {
            inputs["apiVersion"] = undefined /*out*/;
            inputs["kind"] = undefined /*out*/;
            inputs["metadata"] = undefined /*out*/;
            inputs["spec"] = undefined /*out*/;
            inputs["status"] = undefined /*out*/;
        }
        if (!opts.version) {
            opts = pulumi.mergeOptions(opts, { version: utilities.getVersion()});
        }
        super(RabbitmqCluster.__pulumiType, name, inputs, opts);
    }
}

/**
 * The set of arguments for constructing a RabbitmqCluster resource.
 */
export interface RabbitmqClusterArgs {
    readonly apiVersion?: pulumi.Input<"rabbitmq.com/v1beta1">;
    readonly kind?: pulumi.Input<"RabbitmqCluster">;
    readonly metadata?: pulumi.Input<ObjectMeta>;
    /**
     * Spec is the desired state of the RabbitmqCluster Custom Resource.
     */
    readonly spec?: pulumi.Input<inputs.rabbitmq.v1beta1.RabbitmqClusterSpecArgs>;
    /**
     * Status presents the observed state of RabbitmqCluster
     */
    readonly status?: pulumi.Input<inputs.rabbitmq.v1beta1.RabbitmqClusterStatusArgs>;
}
