FROM node:22.14.0-alpine

WORKDIR /app

# Include build artifacts
COPY package.json ./package.json
COPY lerna.json ./lerna.json
COPY node_modules ./node_modules

# Include common node packages
COPY node/packages node/packages/
COPY node/coinstacks/common node/coinstacks/common/
