FROM node:18.12.1-alpine

WORKDIR /app

# Include build artifacts
COPY package.json ./package.json
COPY lerna.json ./lerna.json
COPY node_modules ./node_modules

# Include common packages
COPY node/packages packages/
COPY node/coinstacks/common coinstacks/common/
