/*
Tendermint RPC

Tendermint supports the following RPC protocols:  * URI over HTTP * JSONRPC over HTTP * JSONRPC over websockets  ## Configuration  RPC can be configured by tuning parameters under `[rpc]` table in the `$TMHOME/config/config.toml` file or by using the `--rpc.X` command-line flags.  Default rpc listen address is `tcp://0.0.0.0:26657`. To set another address, set the `laddr` config parameter to desired value. CORS (Cross-Origin Resource Sharing) can be enabled by setting `cors_allowed_origins`, `cors_allowed_methods`, `cors_allowed_headers` config parameters.  ## Arguments  Arguments which expect strings or byte arrays may be passed as quoted strings, like `\"abc\"` or as `0x`-prefixed strings, like `0x616263`.  ## URI/HTTP  A REST like interface.      curl localhost:26657/block?height=5  ## JSONRPC/HTTP  JSONRPC requests can be POST'd to the root RPC endpoint via HTTP.      curl --header \"Content-Type: application/json\" --request POST --data '{\"method\": \"block\", \"params\": [\"5\"], \"id\": 1}' localhost:26657  ## JSONRPC/websockets  JSONRPC requests can be also made via websocket. The websocket endpoint is at `/websocket`, e.g. `localhost:26657/websocket`. Asynchronous RPC functions like event `subscribe` and `unsubscribe` are only available via websockets.  Example using https://github.com/hashrocket/ws:      ws ws://localhost:26657/websocket     > { \"jsonrpc\": \"2.0\", \"method\": \"subscribe\", \"params\": [\"tm.event='NewBlock'\"], \"id\": 1 } 

API version: Master
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// ABCIQueryResponse struct for ABCIQueryResponse
type ABCIQueryResponse struct {
	Error string `json:"error"`
	Result ABCIQueryResponseResult `json:"result"`
	Id int32 `json:"id"`
	Jsonrpc string `json:"jsonrpc"`
}

// NewABCIQueryResponse instantiates a new ABCIQueryResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewABCIQueryResponse(error_ string, result ABCIQueryResponseResult, id int32, jsonrpc string) *ABCIQueryResponse {
	this := ABCIQueryResponse{}
	this.Error = error_
	this.Result = result
	this.Id = id
	this.Jsonrpc = jsonrpc
	return &this
}

// NewABCIQueryResponseWithDefaults instantiates a new ABCIQueryResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewABCIQueryResponseWithDefaults() *ABCIQueryResponse {
	this := ABCIQueryResponse{}
	return &this
}

// GetError returns the Error field value
func (o *ABCIQueryResponse) GetError() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Error
}

// GetErrorOk returns a tuple with the Error field value
// and a boolean to check if the value has been set.
func (o *ABCIQueryResponse) GetErrorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Error, true
}

// SetError sets field value
func (o *ABCIQueryResponse) SetError(v string) {
	o.Error = v
}

// GetResult returns the Result field value
func (o *ABCIQueryResponse) GetResult() ABCIQueryResponseResult {
	if o == nil {
		var ret ABCIQueryResponseResult
		return ret
	}

	return o.Result
}

// GetResultOk returns a tuple with the Result field value
// and a boolean to check if the value has been set.
func (o *ABCIQueryResponse) GetResultOk() (*ABCIQueryResponseResult, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Result, true
}

// SetResult sets field value
func (o *ABCIQueryResponse) SetResult(v ABCIQueryResponseResult) {
	o.Result = v
}

// GetId returns the Id field value
func (o *ABCIQueryResponse) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ABCIQueryResponse) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ABCIQueryResponse) SetId(v int32) {
	o.Id = v
}

// GetJsonrpc returns the Jsonrpc field value
func (o *ABCIQueryResponse) GetJsonrpc() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Jsonrpc
}

// GetJsonrpcOk returns a tuple with the Jsonrpc field value
// and a boolean to check if the value has been set.
func (o *ABCIQueryResponse) GetJsonrpcOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Jsonrpc, true
}

// SetJsonrpc sets field value
func (o *ABCIQueryResponse) SetJsonrpc(v string) {
	o.Jsonrpc = v
}

func (o ABCIQueryResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["error"] = o.Error
	}
	if true {
		toSerialize["result"] = o.Result
	}
	if true {
		toSerialize["id"] = o.Id
	}
	if true {
		toSerialize["jsonrpc"] = o.Jsonrpc
	}
	return json.Marshal(toSerialize)
}

type NullableABCIQueryResponse struct {
	value *ABCIQueryResponse
	isSet bool
}

func (v NullableABCIQueryResponse) Get() *ABCIQueryResponse {
	return v.value
}

func (v *NullableABCIQueryResponse) Set(val *ABCIQueryResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableABCIQueryResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableABCIQueryResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableABCIQueryResponse(val *ABCIQueryResponse) *NullableABCIQueryResponse {
	return &NullableABCIQueryResponse{value: val, isSet: true}
}

func (v NullableABCIQueryResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableABCIQueryResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


