/*
Tendermint RPC

Tendermint supports the following RPC protocols:  * URI over HTTP * JSONRPC over HTTP * JSONRPC over websockets  ## Configuration  RPC can be configured by tuning parameters under `[rpc]` table in the `$TMHOME/config/config.toml` file or by using the `--rpc.X` command-line flags.  Default rpc listen address is `tcp://0.0.0.0:26657`. To set another address, set the `laddr` config parameter to desired value. CORS (Cross-Origin Resource Sharing) can be enabled by setting `cors_allowed_origins`, `cors_allowed_methods`, `cors_allowed_headers` config parameters.  ## Arguments  Arguments which expect strings or byte arrays may be passed as quoted strings, like `\"abc\"` or as `0x`-prefixed strings, like `0x616263`.  ## URI/HTTP  A REST like interface.      curl localhost:26657/block?height=5  ## JSONRPC/HTTP  JSONRPC requests can be POST'd to the root RPC endpoint via HTTP.      curl --header \"Content-Type: application/json\" --request POST --data '{\"method\": \"block\", \"params\": [\"5\"], \"id\": 1}' localhost:26657  ## JSONRPC/websockets  JSONRPC requests can be also made via websocket. The websocket endpoint is at `/websocket`, e.g. `localhost:26657/websocket`. Asynchronous RPC functions like event `subscribe` and `unsubscribe` are only available via websockets.  Example using https://github.com/hashrocket/ws:      ws ws://localhost:26657/websocket     > { \"jsonrpc\": \"2.0\", \"method\": \"subscribe\", \"params\": [\"tm.event='NewBlock'\"], \"id\": 1 } 

API version: Master
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// ConsensusParams struct for ConsensusParams
type ConsensusParams struct {
	Block ConsensusParamsBlock `json:"block"`
	Evidence ConsensusParamsEvidence `json:"evidence"`
	Validator ConsensusParamsValidator `json:"validator"`
}

// NewConsensusParams instantiates a new ConsensusParams object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConsensusParams(block ConsensusParamsBlock, evidence ConsensusParamsEvidence, validator ConsensusParamsValidator) *ConsensusParams {
	this := ConsensusParams{}
	this.Block = block
	this.Evidence = evidence
	this.Validator = validator
	return &this
}

// NewConsensusParamsWithDefaults instantiates a new ConsensusParams object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConsensusParamsWithDefaults() *ConsensusParams {
	this := ConsensusParams{}
	return &this
}

// GetBlock returns the Block field value
func (o *ConsensusParams) GetBlock() ConsensusParamsBlock {
	if o == nil {
		var ret ConsensusParamsBlock
		return ret
	}

	return o.Block
}

// GetBlockOk returns a tuple with the Block field value
// and a boolean to check if the value has been set.
func (o *ConsensusParams) GetBlockOk() (*ConsensusParamsBlock, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Block, true
}

// SetBlock sets field value
func (o *ConsensusParams) SetBlock(v ConsensusParamsBlock) {
	o.Block = v
}

// GetEvidence returns the Evidence field value
func (o *ConsensusParams) GetEvidence() ConsensusParamsEvidence {
	if o == nil {
		var ret ConsensusParamsEvidence
		return ret
	}

	return o.Evidence
}

// GetEvidenceOk returns a tuple with the Evidence field value
// and a boolean to check if the value has been set.
func (o *ConsensusParams) GetEvidenceOk() (*ConsensusParamsEvidence, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Evidence, true
}

// SetEvidence sets field value
func (o *ConsensusParams) SetEvidence(v ConsensusParamsEvidence) {
	o.Evidence = v
}

// GetValidator returns the Validator field value
func (o *ConsensusParams) GetValidator() ConsensusParamsValidator {
	if o == nil {
		var ret ConsensusParamsValidator
		return ret
	}

	return o.Validator
}

// GetValidatorOk returns a tuple with the Validator field value
// and a boolean to check if the value has been set.
func (o *ConsensusParams) GetValidatorOk() (*ConsensusParamsValidator, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Validator, true
}

// SetValidator sets field value
func (o *ConsensusParams) SetValidator(v ConsensusParamsValidator) {
	o.Validator = v
}

func (o ConsensusParams) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["block"] = o.Block
	}
	if true {
		toSerialize["evidence"] = o.Evidence
	}
	if true {
		toSerialize["validator"] = o.Validator
	}
	return json.Marshal(toSerialize)
}

type NullableConsensusParams struct {
	value *ConsensusParams
	isSet bool
}

func (v NullableConsensusParams) Get() *ConsensusParams {
	return v.value
}

func (v *NullableConsensusParams) Set(val *ConsensusParams) {
	v.value = val
	v.isSet = true
}

func (v NullableConsensusParams) IsSet() bool {
	return v.isSet
}

func (v *NullableConsensusParams) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConsensusParams(val *ConsensusParams) *NullableConsensusParams {
	return &NullableConsensusParams{value: val, isSet: true}
}

func (v NullableConsensusParams) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConsensusParams) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


