/*
Tendermint RPC

Tendermint supports the following RPC protocols:  * URI over HTTP * JSONRPC over HTTP * JSONRPC over websockets  ## Configuration  RPC can be configured by tuning parameters under `[rpc]` table in the `$TMHOME/config/config.toml` file or by using the `--rpc.X` command-line flags.  Default rpc listen address is `tcp://0.0.0.0:26657`. To set another address, set the `laddr` config parameter to desired value. CORS (Cross-Origin Resource Sharing) can be enabled by setting `cors_allowed_origins`, `cors_allowed_methods`, `cors_allowed_headers` config parameters.  ## Arguments  Arguments which expect strings or byte arrays may be passed as quoted strings, like `\"abc\"` or as `0x`-prefixed strings, like `0x616263`.  ## URI/HTTP  A REST like interface.      curl localhost:26657/block?height=5  ## JSONRPC/HTTP  JSONRPC requests can be POST'd to the root RPC endpoint via HTTP.      curl --header \"Content-Type: application/json\" --request POST --data '{\"method\": \"block\", \"params\": [\"5\"], \"id\": 1}' localhost:26657  ## JSONRPC/websockets  JSONRPC requests can be also made via websocket. The websocket endpoint is at `/websocket`, e.g. `localhost:26657/websocket`. Asynchronous RPC functions like event `subscribe` and `unsubscribe` are only available via websockets.  Example using https://github.com/hashrocket/ws:      ws ws://localhost:26657/websocket     > { \"jsonrpc\": \"2.0\", \"method\": \"subscribe\", \"params\": [\"tm.event='NewBlock'\"], \"id\": 1 } 

API version: Master
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// NodeInfoOther struct for NodeInfoOther
type NodeInfoOther struct {
	TxIndex *string `json:"tx_index,omitempty"`
	RpcAddress *string `json:"rpc_address,omitempty"`
}

// NewNodeInfoOther instantiates a new NodeInfoOther object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNodeInfoOther() *NodeInfoOther {
	this := NodeInfoOther{}
	return &this
}

// NewNodeInfoOtherWithDefaults instantiates a new NodeInfoOther object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNodeInfoOtherWithDefaults() *NodeInfoOther {
	this := NodeInfoOther{}
	return &this
}

// GetTxIndex returns the TxIndex field value if set, zero value otherwise.
func (o *NodeInfoOther) GetTxIndex() string {
	if o == nil || o.TxIndex == nil {
		var ret string
		return ret
	}
	return *o.TxIndex
}

// GetTxIndexOk returns a tuple with the TxIndex field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NodeInfoOther) GetTxIndexOk() (*string, bool) {
	if o == nil || o.TxIndex == nil {
		return nil, false
	}
	return o.TxIndex, true
}

// HasTxIndex returns a boolean if a field has been set.
func (o *NodeInfoOther) HasTxIndex() bool {
	if o != nil && o.TxIndex != nil {
		return true
	}

	return false
}

// SetTxIndex gets a reference to the given string and assigns it to the TxIndex field.
func (o *NodeInfoOther) SetTxIndex(v string) {
	o.TxIndex = &v
}

// GetRpcAddress returns the RpcAddress field value if set, zero value otherwise.
func (o *NodeInfoOther) GetRpcAddress() string {
	if o == nil || o.RpcAddress == nil {
		var ret string
		return ret
	}
	return *o.RpcAddress
}

// GetRpcAddressOk returns a tuple with the RpcAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NodeInfoOther) GetRpcAddressOk() (*string, bool) {
	if o == nil || o.RpcAddress == nil {
		return nil, false
	}
	return o.RpcAddress, true
}

// HasRpcAddress returns a boolean if a field has been set.
func (o *NodeInfoOther) HasRpcAddress() bool {
	if o != nil && o.RpcAddress != nil {
		return true
	}

	return false
}

// SetRpcAddress gets a reference to the given string and assigns it to the RpcAddress field.
func (o *NodeInfoOther) SetRpcAddress(v string) {
	o.RpcAddress = &v
}

func (o NodeInfoOther) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.TxIndex != nil {
		toSerialize["tx_index"] = o.TxIndex
	}
	if o.RpcAddress != nil {
		toSerialize["rpc_address"] = o.RpcAddress
	}
	return json.Marshal(toSerialize)
}

type NullableNodeInfoOther struct {
	value *NodeInfoOther
	isSet bool
}

func (v NullableNodeInfoOther) Get() *NodeInfoOther {
	return v.value
}

func (v *NullableNodeInfoOther) Set(val *NodeInfoOther) {
	v.value = val
	v.isSet = true
}

func (v NullableNodeInfoOther) IsSet() bool {
	return v.isSet
}

func (v *NullableNodeInfoOther) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNodeInfoOther(val *NodeInfoOther) *NullableNodeInfoOther {
	return &NullableNodeInfoOther{value: val, isSet: true}
}

func (v NullableNodeInfoOther) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNodeInfoOther) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


