/*
Tendermint RPC

Tendermint supports the following RPC protocols:  * URI over HTTP * JSONRPC over HTTP * JSONRPC over websockets  ## Configuration  RPC can be configured by tuning parameters under `[rpc]` table in the `$TMHOME/config/config.toml` file or by using the `--rpc.X` command-line flags.  Default rpc listen address is `tcp://0.0.0.0:26657`. To set another address, set the `laddr` config parameter to desired value. CORS (Cross-Origin Resource Sharing) can be enabled by setting `cors_allowed_origins`, `cors_allowed_methods`, `cors_allowed_headers` config parameters.  ## Arguments  Arguments which expect strings or byte arrays may be passed as quoted strings, like `\"abc\"` or as `0x`-prefixed strings, like `0x616263`.  ## URI/HTTP  A REST like interface.      curl localhost:26657/block?height=5  ## JSONRPC/HTTP  JSONRPC requests can be POST'd to the root RPC endpoint via HTTP.      curl --header \"Content-Type: application/json\" --request POST --data '{\"method\": \"block\", \"params\": [\"5\"], \"id\": 1}' localhost:26657  ## JSONRPC/websockets  JSONRPC requests can be also made via websocket. The websocket endpoint is at `/websocket`, e.g. `localhost:26657/websocket`. Asynchronous RPC functions like event `subscribe` and `unsubscribe` are only available via websockets.  Example using https://github.com/hashrocket/ws:      ws ws://localhost:26657/websocket     > { \"jsonrpc\": \"2.0\", \"method\": \"subscribe\", \"params\": [\"tm.event='NewBlock'\"], \"id\": 1 } 

API version: Master
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// Blockchain struct for Blockchain
type Blockchain struct {
	LastHeight string `json:"last_height"`
	BlockMetas []BlockMeta `json:"block_metas"`
}

// NewBlockchain instantiates a new Blockchain object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBlockchain(lastHeight string, blockMetas []BlockMeta) *Blockchain {
	this := Blockchain{}
	this.LastHeight = lastHeight
	this.BlockMetas = blockMetas
	return &this
}

// NewBlockchainWithDefaults instantiates a new Blockchain object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBlockchainWithDefaults() *Blockchain {
	this := Blockchain{}
	return &this
}

// GetLastHeight returns the LastHeight field value
func (o *Blockchain) GetLastHeight() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LastHeight
}

// GetLastHeightOk returns a tuple with the LastHeight field value
// and a boolean to check if the value has been set.
func (o *Blockchain) GetLastHeightOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.LastHeight, true
}

// SetLastHeight sets field value
func (o *Blockchain) SetLastHeight(v string) {
	o.LastHeight = v
}

// GetBlockMetas returns the BlockMetas field value
func (o *Blockchain) GetBlockMetas() []BlockMeta {
	if o == nil {
		var ret []BlockMeta
		return ret
	}

	return o.BlockMetas
}

// GetBlockMetasOk returns a tuple with the BlockMetas field value
// and a boolean to check if the value has been set.
func (o *Blockchain) GetBlockMetasOk() (*[]BlockMeta, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.BlockMetas, true
}

// SetBlockMetas sets field value
func (o *Blockchain) SetBlockMetas(v []BlockMeta) {
	o.BlockMetas = v
}

func (o Blockchain) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["last_height"] = o.LastHeight
	}
	if true {
		toSerialize["block_metas"] = o.BlockMetas
	}
	return json.Marshal(toSerialize)
}

type NullableBlockchain struct {
	value *Blockchain
	isSet bool
}

func (v NullableBlockchain) Get() *Blockchain {
	return v.value
}

func (v *NullableBlockchain) Set(val *Blockchain) {
	v.value = val
	v.isSet = true
}

func (v NullableBlockchain) IsSet() bool {
	return v.isSet
}

func (v *NullableBlockchain) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBlockchain(val *Blockchain) *NullableBlockchain {
	return &NullableBlockchain{value: val, isSet: true}
}

func (v NullableBlockchain) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBlockchain) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


