/*
Tendermint RPC

Tendermint supports the following RPC protocols:  * URI over HTTP * JSONRPC over HTTP * JSONRPC over websockets  ## Configuration  RPC can be configured by tuning parameters under `[rpc]` table in the `$TMHOME/config/config.toml` file or by using the `--rpc.X` command-line flags.  Default rpc listen address is `tcp://0.0.0.0:26657`. To set another address, set the `laddr` config parameter to desired value. CORS (Cross-Origin Resource Sharing) can be enabled by setting `cors_allowed_origins`, `cors_allowed_methods`, `cors_allowed_headers` config parameters.  ## Arguments  Arguments which expect strings or byte arrays may be passed as quoted strings, like `\"abc\"` or as `0x`-prefixed strings, like `0x616263`.  ## URI/HTTP  A REST like interface.      curl localhost:26657/block?height=5  ## JSONRPC/HTTP  JSONRPC requests can be POST'd to the root RPC endpoint via HTTP.      curl --header \"Content-Type: application/json\" --request POST --data '{\"method\": \"block\", \"params\": [\"5\"], \"id\": 1}' localhost:26657  ## JSONRPC/websockets  JSONRPC requests can be also made via websocket. The websocket endpoint is at `/websocket`, e.g. `localhost:26657/websocket`. Asynchronous RPC functions like event `subscribe` and `unsubscribe` are only available via websockets.  Example using https://github.com/hashrocket/ws:      ws ws://localhost:26657/websocket     > { \"jsonrpc\": \"2.0\", \"method\": \"subscribe\", \"params\": [\"tm.event='NewBlock'\"], \"id\": 1 } 

API version: Master
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// Commit struct for Commit
type Commit struct {
	Type int32 `json:"type"`
	Height string `json:"height"`
	Round int32 `json:"round"`
	BlockId BlockID `json:"block_id"`
	Timestamp string `json:"timestamp"`
	ValidatorAddress string `json:"validator_address"`
	ValidatorIndex int32 `json:"validator_index"`
	Signature string `json:"signature"`
}

// NewCommit instantiates a new Commit object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCommit(type_ int32, height string, round int32, blockId BlockID, timestamp string, validatorAddress string, validatorIndex int32, signature string) *Commit {
	this := Commit{}
	this.Type = type_
	this.Height = height
	this.Round = round
	this.BlockId = blockId
	this.Timestamp = timestamp
	this.ValidatorAddress = validatorAddress
	this.ValidatorIndex = validatorIndex
	this.Signature = signature
	return &this
}

// NewCommitWithDefaults instantiates a new Commit object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCommitWithDefaults() *Commit {
	this := Commit{}
	return &this
}

// GetType returns the Type field value
func (o *Commit) GetType() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *Commit) GetTypeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *Commit) SetType(v int32) {
	o.Type = v
}

// GetHeight returns the Height field value
func (o *Commit) GetHeight() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Height
}

// GetHeightOk returns a tuple with the Height field value
// and a boolean to check if the value has been set.
func (o *Commit) GetHeightOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Height, true
}

// SetHeight sets field value
func (o *Commit) SetHeight(v string) {
	o.Height = v
}

// GetRound returns the Round field value
func (o *Commit) GetRound() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Round
}

// GetRoundOk returns a tuple with the Round field value
// and a boolean to check if the value has been set.
func (o *Commit) GetRoundOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Round, true
}

// SetRound sets field value
func (o *Commit) SetRound(v int32) {
	o.Round = v
}

// GetBlockId returns the BlockId field value
func (o *Commit) GetBlockId() BlockID {
	if o == nil {
		var ret BlockID
		return ret
	}

	return o.BlockId
}

// GetBlockIdOk returns a tuple with the BlockId field value
// and a boolean to check if the value has been set.
func (o *Commit) GetBlockIdOk() (*BlockID, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BlockId, true
}

// SetBlockId sets field value
func (o *Commit) SetBlockId(v BlockID) {
	o.BlockId = v
}

// GetTimestamp returns the Timestamp field value
func (o *Commit) GetTimestamp() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value
// and a boolean to check if the value has been set.
func (o *Commit) GetTimestampOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Timestamp, true
}

// SetTimestamp sets field value
func (o *Commit) SetTimestamp(v string) {
	o.Timestamp = v
}

// GetValidatorAddress returns the ValidatorAddress field value
func (o *Commit) GetValidatorAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ValidatorAddress
}

// GetValidatorAddressOk returns a tuple with the ValidatorAddress field value
// and a boolean to check if the value has been set.
func (o *Commit) GetValidatorAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ValidatorAddress, true
}

// SetValidatorAddress sets field value
func (o *Commit) SetValidatorAddress(v string) {
	o.ValidatorAddress = v
}

// GetValidatorIndex returns the ValidatorIndex field value
func (o *Commit) GetValidatorIndex() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ValidatorIndex
}

// GetValidatorIndexOk returns a tuple with the ValidatorIndex field value
// and a boolean to check if the value has been set.
func (o *Commit) GetValidatorIndexOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ValidatorIndex, true
}

// SetValidatorIndex sets field value
func (o *Commit) SetValidatorIndex(v int32) {
	o.ValidatorIndex = v
}

// GetSignature returns the Signature field value
func (o *Commit) GetSignature() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Signature
}

// GetSignatureOk returns a tuple with the Signature field value
// and a boolean to check if the value has been set.
func (o *Commit) GetSignatureOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Signature, true
}

// SetSignature sets field value
func (o *Commit) SetSignature(v string) {
	o.Signature = v
}

func (o Commit) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["type"] = o.Type
	}
	if true {
		toSerialize["height"] = o.Height
	}
	if true {
		toSerialize["round"] = o.Round
	}
	if true {
		toSerialize["block_id"] = o.BlockId
	}
	if true {
		toSerialize["timestamp"] = o.Timestamp
	}
	if true {
		toSerialize["validator_address"] = o.ValidatorAddress
	}
	if true {
		toSerialize["validator_index"] = o.ValidatorIndex
	}
	if true {
		toSerialize["signature"] = o.Signature
	}
	return json.Marshal(toSerialize)
}

type NullableCommit struct {
	value *Commit
	isSet bool
}

func (v NullableCommit) Get() *Commit {
	return v.value
}

func (v *NullableCommit) Set(val *Commit) {
	v.value = val
	v.isSet = true
}

func (v NullableCommit) IsSet() bool {
	return v.isSet
}

func (v *NullableCommit) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCommit(val *Commit) *NullableCommit {
	return &NullableCommit{value: val, isSet: true}
}

func (v NullableCommit) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCommit) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


