/*
Tendermint RPC

Tendermint supports the following RPC protocols:  * URI over HTTP * JSONRPC over HTTP * JSONRPC over websockets  ## Configuration  RPC can be configured by tuning parameters under `[rpc]` table in the `$TMHOME/config/config.toml` file or by using the `--rpc.X` command-line flags.  Default rpc listen address is `tcp://0.0.0.0:26657`. To set another address, set the `laddr` config parameter to desired value. CORS (Cross-Origin Resource Sharing) can be enabled by setting `cors_allowed_origins`, `cors_allowed_methods`, `cors_allowed_headers` config parameters.  ## Arguments  Arguments which expect strings or byte arrays may be passed as quoted strings, like `\"abc\"` or as `0x`-prefixed strings, like `0x616263`.  ## URI/HTTP  A REST like interface.      curl localhost:26657/block?height=5  ## JSONRPC/HTTP  JSONRPC requests can be POST'd to the root RPC endpoint via HTTP.      curl --header \"Content-Type: application/json\" --request POST --data '{\"method\": \"block\", \"params\": [\"5\"], \"id\": 1}' localhost:26657  ## JSONRPC/websockets  JSONRPC requests can be also made via websocket. The websocket endpoint is at `/websocket`, e.g. `localhost:26657/websocket`. Asynchronous RPC functions like event `subscribe` and `unsubscribe` are only available via websockets.  Example using https://github.com/hashrocket/ws:      ws ws://localhost:26657/websocket     > { \"jsonrpc\": \"2.0\", \"method\": \"subscribe\", \"params\": [\"tm.event='NewBlock'\"], \"id\": 1 } 

API version: Master
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// ErrorResponseAllOf struct for ErrorResponseAllOf
type ErrorResponseAllOf struct {
	Error *string `json:"error,omitempty"`
}

// NewErrorResponseAllOf instantiates a new ErrorResponseAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewErrorResponseAllOf() *ErrorResponseAllOf {
	this := ErrorResponseAllOf{}
	return &this
}

// NewErrorResponseAllOfWithDefaults instantiates a new ErrorResponseAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewErrorResponseAllOfWithDefaults() *ErrorResponseAllOf {
	this := ErrorResponseAllOf{}
	return &this
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *ErrorResponseAllOf) GetError() string {
	if o == nil || o.Error == nil {
		var ret string
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ErrorResponseAllOf) GetErrorOk() (*string, bool) {
	if o == nil || o.Error == nil {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *ErrorResponseAllOf) HasError() bool {
	if o != nil && o.Error != nil {
		return true
	}

	return false
}

// SetError gets a reference to the given string and assigns it to the Error field.
func (o *ErrorResponseAllOf) SetError(v string) {
	o.Error = &v
}

func (o ErrorResponseAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Error != nil {
		toSerialize["error"] = o.Error
	}
	return json.Marshal(toSerialize)
}

type NullableErrorResponseAllOf struct {
	value *ErrorResponseAllOf
	isSet bool
}

func (v NullableErrorResponseAllOf) Get() *ErrorResponseAllOf {
	return v.value
}

func (v *NullableErrorResponseAllOf) Set(val *ErrorResponseAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableErrorResponseAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableErrorResponseAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableErrorResponseAllOf(val *ErrorResponseAllOf) *NullableErrorResponseAllOf {
	return &NullableErrorResponseAllOf{value: val, isSet: true}
}

func (v NullableErrorResponseAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableErrorResponseAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


