/*
Tendermint RPC

Tendermint supports the following RPC protocols:  * URI over HTTP * JSONRPC over HTTP * JSONRPC over websockets  ## Configuration  RPC can be configured by tuning parameters under `[rpc]` table in the `$TMHOME/config/config.toml` file or by using the `--rpc.X` command-line flags.  Default rpc listen address is `tcp://0.0.0.0:26657`. To set another address, set the `laddr` config parameter to desired value. CORS (Cross-Origin Resource Sharing) can be enabled by setting `cors_allowed_origins`, `cors_allowed_methods`, `cors_allowed_headers` config parameters.  ## Arguments  Arguments which expect strings or byte arrays may be passed as quoted strings, like `\"abc\"` or as `0x`-prefixed strings, like `0x616263`.  ## URI/HTTP  A REST like interface.      curl localhost:26657/block?height=5  ## JSONRPC/HTTP  JSONRPC requests can be POST'd to the root RPC endpoint via HTTP.      curl --header \"Content-Type: application/json\" --request POST --data '{\"method\": \"block\", \"params\": [\"5\"], \"id\": 1}' localhost:26657  ## JSONRPC/websockets  JSONRPC requests can be also made via websocket. The websocket endpoint is at `/websocket`, e.g. `localhost:26657/websocket`. Asynchronous RPC functions like event `subscribe` and `unsubscribe` are only available via websockets.  Example using https://github.com/hashrocket/ws:      ws ws://localhost:26657/websocket     > { \"jsonrpc\": \"2.0\", \"method\": \"subscribe\", \"params\": [\"tm.event='NewBlock'\"], \"id\": 1 } 

API version: Master
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// ConsensusParamsValidator struct for ConsensusParamsValidator
type ConsensusParamsValidator struct {
	PubKeyTypes []string `json:"pub_key_types"`
}

// NewConsensusParamsValidator instantiates a new ConsensusParamsValidator object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConsensusParamsValidator(pubKeyTypes []string) *ConsensusParamsValidator {
	this := ConsensusParamsValidator{}
	this.PubKeyTypes = pubKeyTypes
	return &this
}

// NewConsensusParamsValidatorWithDefaults instantiates a new ConsensusParamsValidator object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConsensusParamsValidatorWithDefaults() *ConsensusParamsValidator {
	this := ConsensusParamsValidator{}
	return &this
}

// GetPubKeyTypes returns the PubKeyTypes field value
func (o *ConsensusParamsValidator) GetPubKeyTypes() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.PubKeyTypes
}

// GetPubKeyTypesOk returns a tuple with the PubKeyTypes field value
// and a boolean to check if the value has been set.
func (o *ConsensusParamsValidator) GetPubKeyTypesOk() (*[]string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.PubKeyTypes, true
}

// SetPubKeyTypes sets field value
func (o *ConsensusParamsValidator) SetPubKeyTypes(v []string) {
	o.PubKeyTypes = v
}

func (o ConsensusParamsValidator) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["pub_key_types"] = o.PubKeyTypes
	}
	return json.Marshal(toSerialize)
}

type NullableConsensusParamsValidator struct {
	value *ConsensusParamsValidator
	isSet bool
}

func (v NullableConsensusParamsValidator) Get() *ConsensusParamsValidator {
	return v.value
}

func (v *NullableConsensusParamsValidator) Set(val *ConsensusParamsValidator) {
	v.value = val
	v.isSet = true
}

func (v NullableConsensusParamsValidator) IsSet() bool {
	return v.isSet
}

func (v *NullableConsensusParamsValidator) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConsensusParamsValidator(val *ConsensusParamsValidator) *NullableConsensusParamsValidator {
	return &NullableConsensusParamsValidator{value: val, isSet: true}
}

func (v NullableConsensusParamsValidator) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConsensusParamsValidator) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


