ARG BASE_IMAGE

FROM $BASE_IMAGE

WORKDIR /app/pulumi

COPY package.json package.json

COPY dist/volumeReaper/index.js dist/volumeReaper/index.js
COPY dist/volumeSnapshotClient.js dist/volumeSnapshotClient.js

ENTRYPOINT ["node", "dist/volumeReaper/index.js"]
