ARG BASE_IMAGE

FROM $BASE_IMAGE

WORKDIR /app/pulumi

COPY package.json package.json

COPY dist/volumeReaper/* dist/volumeReaper/
COPY dist/snapper.js dist/snapper.js

ENTRYPOINT ["node", "dist/volumeReaper/index.js"]
