ARG BASE_IMAGE

FROM $BASE_IMAGE

WORKDIR /app/pulumi

COPY package.json package.json
COPY src/volumeReaper src/volumeReaper
COPY dist/volumeReaper dist/volumeReaper

ENTRYPOINT ["node", "dist/volumeReaper/index.js"]
