services:
  api:
    image: unchained-local-go
    environment:
      - GOCACHE=/tmp
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.thorchain-api.rule=Host(`api.thorchain.localhost`)'
      - 'traefik.http.services.thorchain-api.loadbalancer.server.port=3000'
    command: ["sh", "-c", "reflex -r '(pkg|internal|thorchain)' -R 'swagger' -s -- sh -c 'swagger generate spec -w coinstacks/thorchain -o coinstacks/thorchain/api/swagger.json -x protoc-gen-openapiv2 -m && go run cmd/thorchain/main.go -env cmd/thorchain/.env'"]
    working_dir: /app
    volumes:
      - ../..:/app
      - $GOPATH/pkg/mod/cache:/go/pkg/mod/cache
    networks:
      - thorchain

networks:
  thorchain:
    name: thorchain_default
    external: true