version: '3.6'

services:
  unchained-local:
    image: unchained-local
    build:
      context: .
      dockerfile: Dockerfile.local

  watcher:
    image: unchained-local
    working_dir: /app
    command: sh -c "yarn lerna run watch --scope @shapeshiftoss/* --parallel"
    volumes:
      - .:/app

  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.5
    # Enables the web UI and tells Traefik to listen to docker
    command:
      - '--api.insecure=true'
      # Enabling docker provider
      - '--providers.docker=true'
      # Do not expose containers unless explicitly told so
      - '--providers.docker.exposedbydefault=false'
    networks:
      - bitcoin_default
      - ethereum_default
    ports:
      # The HTTP port
      - '80:80'
      # The Web UI (enabled by --api.insecure=true)
      - '8080:8080'
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  bitcoin_default:
    name: bitcoin_default
  ethereum_default:
    name: ethereum_default
