version: '3.6'

services:
  api:
    image: unchained-local-node
    env_file: .env
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.pivx-api.rule=Host(`api.pivx.localhost`)'
      - 'traefik.http.services.pivx-api.loadbalancer.server.port=3000'
    working_dir: /app/coinstacks/pivx/api
    command: yarn nodemon
    volumes:
      - ../..:/app