{
 "title": "General Overview",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "label": "Namespace", "query": "unchained,unchained-dev" },
   {
    "name": "coinstack",
    "label": "Coinstack",
    "query": "arbitrum,arbitrum-nova,avalanche,bitcoin,bitcoincash,bnbsmartchain,cosmos,dogecoin,ethereum,gnosis,litecoin,optimism,polygon,thorchain"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 1 },
   "repeat": "coinstack",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(kube_deployment_status_replicas_ready{namespace=\"$namespace\", deployment=~\"$coinstack-api-.*\"} / kube_deployment_status_replicas{namespace=\"$namespace\", deployment=~\"$coinstack-api-.*\"}) * 100",
     "legendFormat": "$coinstack-api"
    },
    {
     "expr": "(kube_statefulset_status_replicas_ready{namespace=\"$namespace\", statefulset=~\"$coinstack-sts\"} / kube_statefulset_replicas{namespace=\"$namespace\", statefulset=~\"$coinstack-sts\"}) * 100",
     "legendFormat": "$coinstack-sts"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\",pod=~\".*$coinstack-.*\"}[5m])) by (pod, container) / avg(kube_pod_container_resource_limits{namespace=\"$namespace\",pod=~\".*$coinstack-.*\",resource=\"cpu\"}) by (pod, container) * 100",
     "legendFormat": "{{pod}}-{{container}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(container_memory_working_set_bytes{namespace=\"$namespace\",pod=~\".*$coinstack-.*\"}) by (pod, container) / sum(kube_pod_container_resource_limits{namespace=\"$namespace\",pod=~\".*$coinstack-.*\",resource=\"memory\"}) by (pod, container) * 100",
     "legendFormat": "{{pod}}-{{container}}"
    }
   ]
  },
  {
   "title": "Restarts",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total{namespace=\"$namespace\", pod=~\".*$coinstack-.*\"}[$__rate_interval])) by (pod, container)",
     "legendFormat": "{{pod}}-{{container}}"
    }
   ]
  },
  {
   "title": "Arbitrum One",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 },
   "collapsed": true,
   "panels": [
    {
     "title": "WS Connection Count",
     "type": "stat",
     "gridPos": { "h": 12, "w": 3, "x": 0, "y": 58 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(unchained_ws_client_count{coinstack=\"arbitrum\", namespace=\"$namespace\"})"
      }
     ]
    },
    {
     "type": "gauge",
     "gridPos": { "h": 7, "w": 9, "x": 3, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(kube_deployment_status_replicas_ready{namespace=\"$namespace\", deployment=~\"arbitrum-api-.*\"} / kube_deployment_status_replicas{namespace=\"$namespace\", deployment=~\"arbitrum-api-.*\"}) * 100",
       "legendFormat": "API"
      },
      {
       "expr": "(kube_statefulset_status_replicas_ready{namespace=\"$namespace\", statefulset=~\"arbitrum-sts\"} / kube_statefulset_replicas{namespace=\"$namespace\", statefulset=~\"arbitrum-sts\"}) * 100",
       "legendFormat": "STS"
      }
     ]
    },
    {
     "title": "Request Count",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(increase(label_replace(unchained_http_request_count{namespace=\"$namespace\", coinstack=\"arbitrum\", statusCode!=\"404\", route=~\"/api/v1/(info|gas|send|metadata).*\"}, \"endpoint\", \"$1\", \"route\", \"(.*?)(?:\\\\?.*|$)\")[$__rate_interval:])) by (endpoint)",
       "legendFormat": "{{endpoint}}"
      },
      {
       "expr": "sum(increase(label_replace(unchained_http_request_count{namespace=\"$namespace\", coinstack=\"arbitrum\", statusCode!=\"404\", route=~\"/api/v1/account.*\"}, \"endpoint\", \"$1$2\", \"route\", \"(.*/account)(?:\\\\/.*?|\\\\?.*|$)(\\\\/.*?|$)(?:\\\\?.*|$)\")[$__rate_interval:])) by (endpoint)",
       "legendFormat": "{{endpoint}}"
      },
      {
       "expr": "sum(increase(label_replace(unchained_http_request_count{namespace=\"$namespace\", coinstack=\"arbitrum\", statusCode!=\"404\", route=~\"/api/v1/tx.*\"}, \"endpoint\", \"$1\", \"route\", \"(.*/tx).*\")[$__rate_interval:])) by (endpoint)",
       "legendFormat": "{{endpoint}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 5, "w": 9, "x": 3, "y": 65 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kube_deployment_status_replicas_ready{namespace=\"$namespace\", deployment=~\"arbitrum-api-.*\"}",
       "legendFormat": "Available"
      },
      {
       "expr": "kube_deployment_status_replicas{namespace=\"$namespace\", deployment=~\"arbitrum-api-.*\"}",
       "legendFormat": "Total"
      },
      {
       "expr": "kube_statefulset_status_replicas_ready{namespace=\"$namespace\", statefulset=\"arbitrum-sts\"}",
       "legendFormat": "Available"
      },
      {
       "expr": "kube_statefulset_replicas{namespace=\"$namespace\", statefulset=\"arbitrum-sts\"}",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Volume Space Usage",
     "type": "gauge",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max without(instance,node) (\n(\n  topk(1, kubelet_volume_stats_capacity_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$namespace\", persistentvolumeclaim=~\"data-daemon-arbitrum-sts-0\"})\n  -\n  topk(1, kubelet_volume_stats_available_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$namespace\", persistentvolumeclaim=\"data-daemon-arbitrum-sts-0\"})\n)\n/\ntopk(1, kubelet_volume_stats_capacity_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$namespace\", persistentvolumeclaim=\"data-daemon-arbitrum-sts-0\"})\n* 100)",
       "legendFormat": "Daemon"
      },
      {
       "expr": "max without(instance,node) (\n(\n  topk(1, kubelet_volume_stats_capacity_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$namespace\", persistentvolumeclaim=\"data-indexer-arbitrum-sts-0\"})\n  -\n  topk(1, kubelet_volume_stats_available_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$namespace\", persistentvolumeclaim=\"data-indexer-arbitrum-sts-0\"})\n)\n/\ntopk(1, kubelet_volume_stats_capacity_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$namespace\", persistentvolumeclaim=\"data-indexer-arbitrum-sts-0\"})\n* 100)",
       "legendFormat": "Indexer"
      }
     ]
    },
    {
     "title": "Average Request Duration",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 70 },
     "targets": [
      {
       "expr": "(sum(rate(label_replace(unchained_http_request_duration_seconds_sum{namespace=\"$namespace\", coinstack=\"arbitrum\", statusCode!=\"404\", route=~\"/api/v1/(info|gas|send|metadata).*\"}, \"endpoint\", \"$1\", \"route\", \"(.*?)(?:\\\\?.*|$)\")[$__rate_interval:])) by (endpoint) / sum(rate(label_replace(unchained_http_request_duration_seconds_count{namespace=\"$namespace\", coinstack=\"arbitrum\", statusCode!=\"404\", route=~\"/api/v1/(info|gas|send|metadata).*\"}, \"endpoint\", \"$1\", \"route\", \"(.*?)(?:\\\\?.*|$)\")[$__rate_interval:])) by (endpoint))",
       "legendFormat": "{{label_name}}"
      },
      {
       "expr": "(sum(rate(label_replace(unchained_http_request_duration_seconds_sum{namespace=\"$namespace\", coinstack=\"arbitrum\", statusCode!=\"404\", route=~\"/api/v1/account.*\"}, \"endpoint\", \"$1$2\", \"route\", \"(.*/account)(?:\\\\/.*?|\\\\?.*|$)(\\\\/.*?|$)(?:\\\\?.*|$)\")[$__rate_interval:])) by (endpoint) / sum(rate(label_replace(unchained_http_request_duration_seconds_count{namespace=\"$namespace\", coinstack=\"arbitrum\", statusCode!=\"404\", route=~\"/api/v1/account.*\"}, \"endpoint\", \"$1$2\", \"route\", \"(.*/account)(?:\\\\/.*?|\\\\?.*|$)(\\\\/.*?|$)(?:\\\\?.*|$)\")[$__rate_interval:])) by (endpoint))",
       "legendFormat": "{{label_name}}"
      },
      {
       "expr": "(sum(rate(label_replace(unchained_http_request_duration_seconds_sum{namespace=\"$namespace\", coinstack=\"arbitrum\", statusCode!=\"404\", route=~\"/api/v1/tx.*\"}, \"endpoint\", \"$1\", \"route\", \"(.*/tx).*\")[$__rate_interval:])) by (endpoint) / sum(rate(label_replace(unchained_http_request_duration_seconds_count{namespace=\"$namespace\", coinstack=\"arbitrum\", statusCode!=\"404\", route=~\"/api/v1/tx.*\"}, \"endpoint\", \"$1\", \"route\", \"(.*/tx).*\")[$__rate_interval:])) by (endpoint))",
       "legendFormat": "{{label_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Arbitrum Nova",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 },
   "collapsed": true,
   "panels": [
    {
     "title": "WS Connection Count",
     "type": "stat",
     "gridPos": { "h": 12, "w": 3, "x": 0, "y": 83 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(unchained_ws_client_count{coinstack=\"arbitrum-nova\", namespace=\"$namespace\"})"
      }
     ]
    },
    {
     "type": "gauge",
     "gridPos": { "h": 7, "w": 9, "x": 3, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(kube_deployment_status_replicas_ready{namespace=\"$namespace\", deployment=~\"arbitrum-nova-api-.*\"} / kube_deployment_status_replicas{namespace=\"$namespace\", deployment=~\"arbitrum-nova-api-.*\"}) * 100",
       "legendFormat": "API"
      },
      {
       "expr": "(kube_statefulset_status_replicas_ready{namespace=\"$namespace\", statefulset=~\"arbitrum-nova-sts\"} / kube_statefulset_replicas{namespace=\"$namespace\", statefulset=~\"arbitrum-nova-sts\"}) * 100",
       "legendFormat": "STS"
      }
     ]
    },
    {
     "title": "Request Count",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(increase(label_replace(unchained_http_request_count{namespace=\"$namespace\", coinstack=\"arbitrum-nova\", statusCode!=\"404\", route=~\"/api/v1/(info|gas|send|metadata).*\"}, \"endpoint\", \"$1\", \"route\", \"(.*?)(?:\\\\?.*|$)\")[$__rate_interval:])) by (endpoint)",
       "legendFormat": "{{endpoint}}"
      },
      {
       "expr": "sum(increase(label_replace(unchained_http_request_count{namespace=\"$namespace\", coinstack=\"arbitrum-nova\", statusCode!=\"404\", route=~\"/api/v1/account.*\"}, \"endpoint\", \"$1$2\", \"route\", \"(.*/account)(?:\\\\/.*?|\\\\?.*|$)(\\\\/.*?|$)(?:\\\\?.*|$)\")[$__rate_interval:])) by (endpoint)",
       "legendFormat": "{{endpoint}}"
      },
      {
       "expr": "sum(increase(label_replace(unchained_http_request_count{namespace=\"$namespace\", coinstack=\"arbitrum-nova\", statusCode!=\"404\", route=~\"/api/v1/tx.*\"}, \"endpoint\", \"$1\", \"route\", \"(.*/tx).*\")[$__rate_interval:])) by (endpoint)",
       "legendFormat": "{{endpoint}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 5, "w": 9, "x": 3, "y": 90 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kube_deployment_status_replicas_ready{namespace=\"$namespace\", deployment=~\"arbitrum-nova-api-.*\"}",
       "legendFormat": "Available"
      },
      {
       "expr": "kube_deployment_status_replicas{namespace=\"$namespace\", deployment=~\"arbitrum-nova-api-.*\"}",
       "legendFormat": "Total"
      },
      {
       "expr": "kube_statefulset_status_replicas_ready{namespace=\"$namespace\", statefulset=\"arbitrum-nova-sts\"}",
       "legendFormat": "Available"
      },
      {
       "expr": "kube_statefulset_replicas{namespace=\"$namespace\", statefulset=\"arbitrum-nova-sts\"}",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Volume Space Usage",
     "type": "gauge",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 95 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max without(instance,node) (\n(\n  topk(1, kubelet_volume_stats_capacity_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$namespace\", persistentvolumeclaim=~\"data-daemon-arbitrum-nova-sts-0\"})\n  -\n  topk(1, kubelet_volume_stats_available_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$namespace\", persistentvolumeclaim=\"data-daemon-arbitrum-nova-sts-0\"})\n)\n/\ntopk(1, kubelet_volume_stats_capacity_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$namespace\", persistentvolumeclaim=\"data-daemon-arbitrum-nova-sts-0\"})\n* 100)",
       "legendFormat": "Daemon"
      },
      {
       "expr": "max without(instance,node) (\n(\n  topk(1, kubelet_volume_stats_capacity_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$namespace\", persistentvolumeclaim=\"data-indexer-arbitrum-nova-sts-0\"})\n  -\n  topk(1, kubelet_volume_stats_available_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$namespace\", persistentvolumeclaim=\"data-indexer-arbitrum-nova-sts-0\"})\n)\n/\ntopk(1, kubelet_volume_stats_capacity_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$namespace\", persistentvolumeclaim=\"data-indexer-arbitrum-nova-sts-0\"})\n* 100)",
       "legendFormat": "Indexer"
      }
     ]
    },
    {
     "title": "Average Request Duration",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 95 },
     "targets": [
      {
       "expr": "(sum(rate(label_replace(unchained_http_request_duration_seconds_sum{namespace=\"$namespace\", coinstack=\"arbitrum-nova\", statusCode!=\"404\", route=~\"/api/v1/(info|gas|send|metadata).*\"}, \"endpoint\", \"$1\", \"route\", \"(.*?)(?:\\\\?.*|$)\")[$__rate_interval:])) by (endpoint) / sum(rate(label_replace(unchained_http_request_duration_seconds_count{namespace=\"$namespace\", coinstack=\"arbitrum-nova\", statusCode!=\"404\", route=~\"/api/v1/(info|gas|send|metadata).*\"}, \"endpoint\", \"$1\", \"route\", \"(.*?)(?:\\\\?.*|$)\")[$__rate_interval:])) by (endpoint))",
       "legendFormat": "{{label_name}}"
      },
      {
       "expr": "(sum(rate(label_replace(unchained_http_request_duration_seconds_sum{namespace=\"$namespace\", coinstack=\"arbitrum-nova\", statusCode!=\"404\", route=~\"/api/v1/account.*\"}, \"endpoint\", \"$1$2\", \"route\", \"(.*/account)(?:\\\\/.*?|\\\\?.*|$)(\\\\/.*?|$)(?:\\\\?.*|$)\")[$__rate_interval:])) by (endpoint) / sum(rate(label_replace(unchained_http_request_duration_seconds_count{namespace=\"$namespace\", coinstack=\"arbitrum-nova\", statusCode!=\"404\", route=~\"/api/v1/account.*\"}, \"endpoint\", \"$1$2\", \"route\", \"(.*/account)(?:\\\\/.*?|\\\\?.*|$)(\\\\/.*?|$)(?:\\\\?.*|$)\")[$__rate_interval:])) by (endpoint))",
       "legendFormat": "{{label_name}}"
      },
      {
       "expr": "(sum(rate(label_replace(unchained_http_request_duration_seconds_sum{namespace=\"$namespace\", coinstack=\"arbitrum-nova\", statusCode!=\"404\", route=~\"/api/v1/tx.*\"}, \"endpoint\", \"$1\", \"route\", \"(.*/tx).*\")[$__rate_interval:])) by (endpoint) / sum(rate(label_replace(unchained_http_request_duration_seconds_count{namespace=\"$namespace\", coinstack=\"arbitrum-nova\", statusCode!=\"404\", route=~\"/api/v1/tx.*\"}, \"endpoint\", \"$1\", \"route\", \"(.*/tx).*\")[$__rate_interval:])) by (endpoint))",
       "legendFormat": "{{label_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Avalanche",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 },
   "collapsed": true,
   "panels": [
    {
     "title": "WS Connection Count",
     "type": "stat",
     "gridPos": { "h": 12, "w": 3, "x": 0, "y": 83 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(unchained_ws_client_count{coinstack=\"avalanche\", namespace=\"$namespace\"})"
      }
     ]
    },
    {
     "type": "gauge",
     "gridPos": { "h": 7, "w": 9, "x": 3, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(kube_deployment_status_replicas_ready{namespace=\"$namespace\", deployment=~\"avalanche-api-.*\"} / kube_deployment_status_replicas{namespace=\"$namespace\", deployment=~\"avalanche-api-.*\"}) * 100",
       "legendFormat": "API"
      },
      {
       "expr": "(kube_statefulset_status_replicas_ready{namespace=\"$namespace\", statefulset=~\"avalanche-sts\"} / kube_statefulset_replicas{namespace=\"$namespace\", statefulset=~\"avalanche-sts\"}) * 100",
       "legendFormat": "STS"
      }
     ]
    },
    {
     "title": "Request Count",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(increase(label_replace(unchained_http_request_count{namespace=\"$namespace\", coinstack=\"avalanche\", statusCode!=\"404\", route=~\"/api/v1/(info|gas|send|metadata).*\"}, \"endpoint\", \"$1\", \"route\", \"(.*?)(?:\\\\?.*|$)\")[$__rate_interval:])) by (endpoint)",
       "legendFormat": "{{endpoint}}"
      },
      {
       "expr": "sum(increase(label_replace(unchained_http_request_count{namespace=\"$namespace\", coinstack=\"avalanche\", statusCode!=\"404\", route=~\"/api/v1/account.*\"}, \"endpoint\", \"$1$2\", \"route\", \"(.*/account)(?:\\\\/.*?|\\\\?.*|$)(\\\\/.*?|$)(?:\\\\?.*|$)\")[$__rate_interval:])) by (endpoint)",
       "legendFormat": "{{endpoint}}"
      },
      {
       "expr": "sum(increase(label_replace(unchained_http_request_count{namespace=\"$namespace\", coinstack=\"avalanche\", statusCode!=\"404\", route=~\"/api/v1/tx.*\"}, \"endpoint\", \"$1\", \"route\", \"(.*/tx).*\")[$__rate_interval:])) by (endpoint)",
       "legendFormat": "{{endpoint}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 5, "w": 9, "x": 3, "y": 90 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kube_deployment_status_replicas_ready{namespace=\"$namespace\", deployment=~\"avalanche-api-.*\"}",
       "legendFormat": "Available"
      },
      {
       "expr": "kube_deployment_status_replicas{namespace=\"$namespace\", deployment=~\"avalanche-api-.*\"}",
       "legendFormat": "Total"
      },
      {
       "expr": "kube_statefulset_status_replicas_ready{namespace=\"$namespace\", statefulset=\"avalanche-sts\"}",
       "legendFormat": "Available"
      },
      {
       "expr": "kube_statefulset_replicas{namespace=\"$namespace\", statefulset=\"avalanche-sts\"}",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Volume Space Usage",
     "type": "gauge",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 95 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max without(instance,node) (\n(\n  topk(1, kubelet_volume_stats_capacity_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$namespace\", persistentvolumeclaim=~\"data-daemon-avalanche-sts-0\"})\n  -\n  topk(1, kubelet_volume_stats_available_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$namespace\", persistentvolumeclaim=\"data-daemon-avalanche-sts-0\"})\n)\n/\ntopk(1, kubelet_volume_stats_capacity_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$namespace\", persistentvolumeclaim=\"data-daemon-avalanche-sts-0\"})\n* 100)\n",
       "legendFormat": "Daemon"
      },
      {
       "expr": "max without(instance,node) (\n(\n  topk(1, kubelet_volume_stats_capacity_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$namespace\", persistentvolumeclaim=\"data-indexer-avalanche-sts-0\"})\n  -\n  topk(1, kubelet_volume_stats_available_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$namespace\", persistentvolumeclaim=\"data-indexer-avalanche-sts-0\"})\n)\n/\ntopk(1, kubelet_volume_stats_capacity_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$namespace\", persistentvolumeclaim=\"data-indexer-avalanche-sts-0\"})\n* 100)",
       "legendFormat": "Indexer"
      }
     ]
    },
    {
     "title": "Average Request Duration",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 95 },
     "targets": [
      {
       "expr": "(sum(rate(label_replace(unchained_http_request_duration_seconds_sum{namespace=\"$namespace\", coinstack=\"avalanche\", statusCode!=\"404\", route=~\"/api/v1/(info|gas|send|metadata).*\"}, \"endpoint\", \"$1\", \"route\", \"(.*?)(?:\\\\?.*|$)\")[$__rate_interval:])) by (endpoint) / sum(rate(label_replace(unchained_http_request_duration_seconds_count{namespace=\"$namespace\", coinstack=\"avalanche\", statusCode!=\"404\", route=~\"/api/v1/(info|gas|send|metadata).*\"}, \"endpoint\", \"$1\", \"route\", \"(.*?)(?:\\\\?.*|$)\")[$__rate_interval:])) by (endpoint))",
       "legendFormat": "{{label_name}}"
      },
      {
       "expr": "(sum(rate(label_replace(unchained_http_request_duration_seconds_sum{namespace=\"$namespace\", coinstack=\"avalanche\", statusCode!=\"404\", route=~\"/api/v1/account.*\"}, \"endpoint\", \"$1$2\", \"route\", \"(.*/account)(?:\\\\/.*?|\\\\?.*|$)(\\\\/.*?|$)(?:\\\\?.*|$)\")[$__rate_interval:])) by (endpoint) / sum(rate(label_replace(unchained_http_request_duration_seconds_count{namespace=\"$namespace\", coinstack=\"avalanche\", statusCode!=\"404\", route=~\"/api/v1/account.*\"}, \"endpoint\", \"$1$2\", \"route\", \"(.*/account)(?:\\\\/.*?|\\\\?.*|$)(\\\\/.*?|$)(?:\\\\?.*|$)\")[$__rate_interval:])) by (endpoint))",
       "legendFormat": "{{label_name}}"
      },
      {
       "expr": "(sum(rate(label_replace(unchained_http_request_duration_seconds_sum{namespace=\"$namespace\", coinstack=\"avalanche\", statusCode!=\"404\", route=~\"/api/v1/tx.*\"}, \"endpoint\", \"$1\", \"route\", \"(.*/tx).*\")[$__rate_interval:])) by (endpoint) / sum(rate(label_replace(unchained_http_request_duration_seconds_count{namespace=\"$namespace\", coinstack=\"avalanche\", statusCode!=\"404\", route=~\"/api/v1/tx.*\"}, \"endpoint\", \"$1\", \"route\", \"(.*/tx).*\")[$__rate_interval:])) by (endpoint))",
       "legendFormat": "{{label_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "BNB Smart Chain",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 },
   "collapsed": true,
   "panels": [
    {
     "title": "WS Connection Count",
     "type": "stat",
     "gridPos": { "h": 12, "w": 3, "x": 0, "y": 55 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(unchained_ws_client_count{coinstack=\"bnbsmartchain\", namespace=\"$namespace\"})"
      }
     ]
    },
    {
     "type": "gauge",
     "gridPos": { "h": 7, "w": 9, "x": 3, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(kube_deployment_status_replicas_ready{namespace=\"$namespace\", deployment=~\"bnbsmartchain-api-.*\"} / kube_deployment_status_replicas{namespace=\"$namespace\", deployment=~\"bnbsmartchain-api-.*\"}) * 100",
       "legendFormat": "API"
      },
      {
       "expr": "(kube_statefulset_status_replicas_ready{namespace=\"$namespace\", statefulset=~\"bnbsmartchain-sts\"} / kube_statefulset_replicas{namespace=\"$namespace\", statefulset=~\"bnbsmartchain-sts\"}) * 100",
       "legendFormat": "STS"
      }
     ]
    },
    {
     "title": "Request Count",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(increase(label_replace(unchained_http_request_count{namespace=\"$namespace\", coinstack=\"bnbsmartchain\", statusCode!=\"404\", route=~\"/api/v1/(info|gas|send|metadata).*\"}, \"endpoint\", \"$1\", \"route\", \"(.*?)(?:\\\\?.*|$)\")[$__rate_interval:])) by (endpoint)",
       "legendFormat": "{{endpoint}}"
      },
      {
       "expr": "sum(increase(label_replace(unchained_http_request_count{namespace=\"$namespace\", coinstack=\"bnbsmartchain\", statusCode!=\"404\", route=~\"/api/v1/account.*\"}, \"endpoint\", \"$1$2\", \"route\", \"(.*/account)(?:\\\\/.*?|\\\\?.*|$)(\\\\/.*?|$)(?:\\\\?.*|$)\")[$__rate_interval:])) by (endpoint)",
       "legendFormat": "{{endpoint}}"
      },
      {
       "expr": "sum(increase(label_replace(unchained_http_request_count{namespace=\"$namespace\", coinstack=\"bnbsmartchain\", statusCode!=\"404\", route=~\"/api/v1/tx.*\"}, \"endpoint\", \"$1\", \"route\", \"(.*/tx).*\")[$__rate_interval:])) by (endpoint)",
       "legendFormat": "{{endpoint}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 5, "w": 9, "x": 3, "y": 62 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kube_deployment_status_replicas_ready{namespace=\"$namespace\", deployment=~\"bnbsmartchain-api-.*\"}",
       "legendFormat": "Available"
      },
      {
       "expr": "kube_deployment_status_replicas{namespace=\"$namespace\", deployment=~\"bnbsmartchain-api-.*\"}",
       "legendFormat": "Total"
      },
      {
       "expr": "kube_statefulset_status_replicas_ready{namespace=\"$namespace\", statefulset=\"bnbsmartchain-sts\"}",
       "legendFormat": "Available"
      },
      {
       "expr": "kube_statefulset_replicas{namespace=\"$namespace\", statefulset=\"bnbsmartchain-sts\"}",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Volume Space Usage",
     "type": "gauge",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max without(instance,node) (\n(\n  topk(1, kubelet_volume_stats_capacity_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$namespace\", persistentvolumeclaim=~\"data-daemon-bnbsmartchain-sts-0\"})\n  -\n  topk(1, kubelet_volume_stats_available_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$namespace\", persistentvolumeclaim=\"data-daemon-bnbsmartchain-sts-0\"})\n)\n/\ntopk(1, kubelet_volume_stats_capacity_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$namespace\", persistentvolumeclaim=\"data-daemon-bnbsmartchain-sts-0\"})\n* 100)\n",
       "legendFormat": "Daemon"
      },
      {
       "expr": "max without(instance,node) (\n(\n  topk(1, kubelet_volume_stats_capacity_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$namespace\", persistentvolumeclaim=\"data-indexer-bnbsmartchain-sts-0\"})\n  -\n  topk(1, kubelet_volume_stats_available_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$namespace\", persistentvolumeclaim=\"data-indexer-bnbsmartchain-sts-0\"})\n)\n/\ntopk(1, kubelet_volume_stats_capacity_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$namespace\", persistentvolumeclaim=\"data-indexer-bnbsmartchain-sts-0\"})\n* 100)",
       "legendFormat": "Indexer"
      }
     ]
    },
    {
     "title": "Average Request Duration",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 67 },
     "targets": [
      {
       "expr": "(sum(rate(label_replace(unchained_http_request_duration_seconds_sum{namespace=\"$namespace\", coinstack=\"bnbsmartchain\", statusCode!=\"404\", route=~\"/api/v1/(info|gas|send|metadata).*\"}, \"endpoint\", \"$1\", \"route\", \"(.*?)(?:\\\\?.*|$)\")[$__rate_interval:])) by (endpoint) / sum(rate(label_replace(unchained_http_request_duration_seconds_count{namespace=\"$namespace\", coinstack=\"bnbsmartchain\", statusCode!=\"404\", route=~\"/api/v1/(info|gas|send|metadata).*\"}, \"endpoint\", \"$1\", \"route\", \"(.*?)(?:\\\\?.*|$)\")[$__rate_interval:])) by (endpoint))",
       "legendFormat": "{{label_name}}"
      },
      {
       "expr": "(sum(rate(label_replace(unchained_http_request_duration_seconds_sum{namespace=\"$namespace\", coinstack=\"bnbsmartchain\", statusCode!=\"404\", route=~\"/api/v1/account.*\"}, \"endpoint\", \"$1$2\", \"route\", \"(.*/account)(?:\\\\/.*?|\\\\?.*|$)(\\\\/.*?|$)(?:\\\\?.*|$)\")[$__rate_interval:])) by (endpoint) / sum(rate(label_replace(unchained_http_request_duration_seconds_count{namespace=\"$namespace\", coinstack=\"bnbsmartchain\", statusCode!=\"404\", route=~\"/api/v1/account.*\"}, \"endpoint\", \"$1$2\", \"route\", \"(.*/account)(?:\\\\/.*?|\\\\?.*|$)(\\\\/.*?|$)(?:\\\\?.*|$)\")[$__rate_interval:])) by (endpoint))",
       "legendFormat": "{{label_name}}"
      },
      {
       "expr": "(sum(rate(label_replace(unchained_http_request_duration_seconds_sum{namespace=\"$namespace\", coinstack=\"bnbsmartchain\", statusCode!=\"404\", route=~\"/api/v1/tx.*\"}, \"endpoint\", \"$1\", \"route\", \"(.*/tx).*\")[$__rate_interval:])) by (endpoint) / sum(rate(label_replace(unchained_http_request_duration_seconds_count{namespace=\"$namespace\", coinstack=\"bnbsmartchain\", statusCode!=\"404\", route=~\"/api/v1/tx.*\"}, \"endpoint\", \"$1\", \"route\", \"(.*/tx).*\")[$__rate_interval:])) by (endpoint))",
       "legendFormat": "{{label_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Bitcoin",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 },
   "collapsed": true,
   "panels": [
    {
     "title": "WS Connection Count",
     "type": "stat",
     "gridPos": { "h": 12, "w": 3, "x": 0, "y": 56 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(unchained_ws_client_count{coinstack=\"bitcoin\", namespace=\"$namespace\"})"
      }
     ]
    },
    {
     "type": "gauge",
     "gridPos": { "h": 7, "w": 9, "x": 3, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(kube_deployment_status_replicas_ready{namespace=\"$namespace\", deployment=~\"bitcoin-api-.*\"} / kube_deployment_status_replicas{namespace=\"$namespace\", deployment=~\"bitcoin-api-.*\"}) * 100",
       "legendFormat": "API"
      },
      {
       "expr": "(kube_statefulset_status_replicas_ready{namespace=\"$namespace\", statefulset=~\"bitcoin-sts\"} / kube_statefulset_replicas{namespace=\"$namespace\", statefulset=~\"bitcoin-sts\"}) * 100",
       "legendFormat": "STS"
      }
     ]
    },
    {
     "title": "Request Count",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(increase(label_replace(unchained_http_request_count{namespace=\"$namespace\", coinstack=\"bitcoin\", statusCode!=\"404\", route=~\"/api/v1/(info|fees|send).*\"}, \"endpoint\", \"$1\", \"route\", \"(.*?)(?:\\\\?.*|$)\")[$__rate_interval:])) by (endpoint)",
       "legendFormat": "{{endpoint}}"
      },
      {
       "expr": "sum(increase(label_replace(unchained_http_request_count{namespace=\"$namespace\", coinstack=\"bitcoin\", statusCode!=\"404\", route=~\"/api/v1/account.*\"}, \"endpoint\", \"$1$2\", \"route\", \"(.*/account)(?:\\\\/.*?|\\\\?.*|$)(\\\\/.*?|$)(?:\\\\?.*|$)\")[$__rate_interval:])) by (endpoint)",
       "legendFormat": "{{endpoint}}"
      },
      {
       "expr": "sum(increase(label_replace(unchained_http_request_count{namespace=\"$namespace\", coinstack=\"bitcoin\", statusCode!=\"404\", route=~\"/api/v1/tx.*\"}, \"endpoint\", \"$1\", \"route\", \"(.*/tx).*\")[$__rate_interval:])) by (endpoint)",
       "legendFormat": "{{endpoint}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 5, "w": 9, "x": 3, "y": 63 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kube_deployment_status_replicas_ready{namespace=\"$namespace\", deployment=~\"bitcoin-api-.*\"}",
       "legendFormat": "Available"
      },
      {
       "expr": "kube_deployment_status_replicas{namespace=\"$namespace\", deployment=~\"bitcoin-api-.*\"}",
       "legendFormat": "Total"
      },
      {
       "expr": "kube_statefulset_status_replicas_ready{namespace=\"$namespace\", statefulset=\"bitcoin-sts\"}",
       "legendFormat": "Available"
      },
      {
       "expr": "kube_statefulset_replicas{namespace=\"$namespace\", statefulset=\"bitcoin-sts\"}",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Volume Space Usage",
     "type": "gauge",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max without(instance,node) (\n(\n  topk(1, kubelet_volume_stats_capacity_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$namespace\", persistentvolumeclaim=~\"data-daemon-bitcoin-sts-0\"})\n  -\n  topk(1, kubelet_volume_stats_available_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$namespace\", persistentvolumeclaim=\"data-daemon-bitcoin-sts-0\"})\n)\n/\ntopk(1, kubelet_volume_stats_capacity_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$namespace\", persistentvolumeclaim=\"data-daemon-bitcoin-sts-0\"})\n* 100)\n",
       "legendFormat": "Daemon"
      },
      {
       "expr": "max without(instance,node) (\n(\n  topk(1, kubelet_volume_stats_capacity_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$namespace\", persistentvolumeclaim=\"data-indexer-bitcoin-sts-0\"})\n  -\n  topk(1, kubelet_volume_stats_available_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$namespace\", persistentvolumeclaim=\"data-indexer-bitcoin-sts-0\"})\n)\n/\ntopk(1, kubelet_volume_stats_capacity_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$namespace\", persistentvolumeclaim=\"data-indexer-bitcoin-sts-0\"})\n* 100)",
       "legendFormat": "Indexer"
      }
     ]
    },
    {
     "title": "Average Request Duration",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 68 },
     "targets": [
      {
       "expr": "(sum(rate(label_replace(unchained_http_request_duration_seconds_sum{namespace=\"$namespace\", coinstack=\"bitcoin\", statusCode!=\"404\", route=~\"/api/v1/(info|fees|send).*\"}, \"endpoint\", \"$1\", \"route\", \"(.*?)(?:\\\\?.*|$)\")[$__rate_interval:])) by (endpoint) / sum(rate(label_replace(unchained_http_request_duration_seconds_count{namespace=\"$namespace\", coinstack=\"bitcoin\", statusCode!=\"404\", route=~\"/api/v1/(info|fees|send).*\"}, \"endpoint\", \"$1\", \"route\", \"(.*?)(?:\\\\?.*|$)\")[$__rate_interval:])) by (endpoint))",
       "legendFormat": "{{label_name}}"
      },
      {
       "expr": "(sum(rate(label_replace(unchained_http_request_duration_seconds_sum{namespace=\"$namespace\", coinstack=\"bitcoin\", statusCode!=\"404\", route=~\"/api/v1/account.*\"}, \"endpoint\", \"$1$2\", \"route\", \"(.*/account)(?:\\\\/.*?|\\\\?.*|$)(\\\\/.*?|$)(?:\\\\?.*|$)\")[$__rate_interval:])) by (endpoint) / sum(rate(label_replace(unchained_http_request_duration_seconds_count{namespace=\"$namespace\", coinstack=\"bitcoin\", statusCode!=\"404\", route=~\"/api/v1/account.*\"}, \"endpoint\", \"$1$2\", \"route\", \"(.*/account)(?:\\\\/.*?|\\\\?.*|$)(\\\\/.*?|$)(?:\\\\?.*|$)\")[$__rate_interval:])) by (endpoint))",
       "legendFormat": "{{label_name}}"
      },
      {
       "expr": "(sum(rate(label_replace(unchained_http_request_duration_seconds_sum{namespace=\"$namespace\", coinstack=\"bitcoin\", statusCode!=\"404\", route=~\"/api/v1/tx.*\"}, \"endpoint\", \"$1\", \"route\", \"(.*/tx).*\")[$__rate_interval:])) by (endpoint) / sum(rate(label_replace(unchained_http_request_duration_seconds_count{namespace=\"$namespace\", coinstack=\"bitcoin\", statusCode!=\"404\", route=~\"/api/v1/tx.*\"}, \"endpoint\", \"$1\", \"route\", \"(.*/tx).*\")[$__rate_interval:])) by (endpoint))",
       "legendFormat": "{{label_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Bitcoin Cash",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 },
   "collapsed": true,
   "panels": [
    {
     "title": "WS Connection Count",
     "type": "stat",
     "gridPos": { "h": 12, "w": 3, "x": 0, "y": 57 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(unchained_ws_client_count{coinstack=\"bitcoincash\", namespace=\"$namespace\"})"
      }
     ]
    },
    {
     "type": "gauge",
     "gridPos": { "h": 7, "w": 9, "x": 3, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(kube_deployment_status_replicas_ready{namespace=\"$namespace\", deployment=~\"bitcoincash-api-.*\"} / kube_deployment_status_replicas{namespace=\"$namespace\", deployment=~\"bitcoincash-api-.*\"}) * 100",
       "legendFormat": "API"
      },
      {
       "expr": "(kube_statefulset_status_replicas_ready{namespace=\"$namespace\", statefulset=~\"bitcoincash-sts\"} / kube_statefulset_replicas{namespace=\"$namespace\", statefulset=~\"bitcoincash-sts\"}) * 100",
       "legendFormat": "STS"
      }
     ]
    },
    {
     "title": "Request Count",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(increase(label_replace(unchained_http_request_count{namespace=\"$namespace\", coinstack=\"bitcoincash\", statusCode!=\"404\", route=~\"/api/v1/(info|fees|send).*\"}, \"endpoint\", \"$1\", \"route\", \"(.*?)(?:\\\\?.*|$)\")[$__rate_interval:])) by (endpoint)",
       "legendFormat": "{{endpoint}}"
      },
      {
       "expr": "sum(increase(label_replace(unchained_http_request_count{namespace=\"$namespace\", coinstack=\"bitcoincash\", statusCode!=\"404\", route=~\"/api/v1/account.*\"}, \"endpoint\", \"$1$2\", \"route\", \"(.*/account)(?:\\\\/.*?|\\\\?.*|$)(\\\\/.*?|$)(?:\\\\?.*|$)\")[$__rate_interval:])) by (endpoint)",
       "legendFormat": "{{endpoint}}"
      },
      {
       "expr": "sum(increase(label_replace(unchained_http_request_count{namespace=\"$namespace\", coinstack=\"bitcoincash\", statusCode!=\"404\", route=~\"/api/v1/tx.*\"}, \"endpoint\", \"$1\", \"route\", \"(.*/tx).*\")[$__rate_interval:])) by (endpoint)",
       "legendFormat": "{{endpoint}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 5, "w": 9, "x": 3, "y": 64 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kube_deployment_status_replicas_ready{namespace=\"$namespace\", deployment=~\"bitcoincash-api-.*\"}",
       "legendFormat": "Available"
      },
      {
       "expr": "kube_deployment_status_replicas{namespace=\"$namespace\", deployment=~\"bitcoincash-api-.*\"}",
       "legendFormat": "Total"
      },
      {
       "expr": "kube_statefulset_status_replicas_ready{namespace=\"$namespace\", statefulset=\"bitcoincash-sts\"}",
       "legendFormat": "Available"
      },
      {
       "expr": "kube_statefulset_replicas{namespace=\"$namespace\", statefulset=\"bitcoincash-sts\"}",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Volume Space Usage",
     "type": "gauge",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max without(instance,node) (\n(\n  topk(1, kubelet_volume_stats_capacity_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$namespace\", persistentvolumeclaim=~\"data-daemon-bitcoincash-sts-0\"})\n  -\n  topk(1, kubelet_volume_stats_available_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$namespace\", persistentvolumeclaim=\"data-daemon-bitcoincash-sts-0\"})\n)\n/\ntopk(1, kubelet_volume_stats_capacity_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$namespace\", persistentvolumeclaim=\"data-daemon-bitcoincash-sts-0\"})\n* 100)\n",
       "legendFormat": "Daemon"
      },
      {
       "expr": "max without(instance,node) (\n(\n  topk(1, kubelet_volume_stats_capacity_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$namespace\", persistentvolumeclaim=\"data-indexer-bitcoincash-sts-0\"})\n  -\n  topk(1, kubelet_volume_stats_available_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$namespace\", persistentvolumeclaim=\"data-indexer-bitcoincash-sts-0\"})\n)\n/\ntopk(1, kubelet_volume_stats_capacity_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$namespace\", persistentvolumeclaim=\"data-indexer-bitcoincash-sts-0\"})\n* 100)",
       "legendFormat": "Indexer"
      }
     ]
    },
    {
     "title": "Average Request Duration",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 69 },
     "targets": [
      {
       "expr": "(sum(rate(label_replace(unchained_http_request_duration_seconds_sum{namespace=\"$namespace\", coinstack=\"bitcoincash\", statusCode!=\"404\", route=~\"/api/v1/(info|fees|send).*\"}, \"endpoint\", \"$1\", \"route\", \"(.*?)(?:\\\\?.*|$)\")[$__rate_interval:])) by (endpoint) / sum(rate(label_replace(unchained_http_request_duration_seconds_count{namespace=\"$namespace\", coinstack=\"bitcoincash\", statusCode!=\"404\", route=~\"/api/v1/(info|fees|send).*\"}, \"endpoint\", \"$1\", \"route\", \"(.*?)(?:\\\\?.*|$)\")[$__rate_interval:])) by (endpoint))",
       "legendFormat": "{{label_name}}"
      },
      {
       "expr": "(sum(rate(label_replace(unchained_http_request_duration_seconds_sum{namespace=\"$namespace\", coinstack=\"bitcoincash\", statusCode!=\"404\", route=~\"/api/v1/account.*\"}, \"endpoint\", \"$1$2\", \"route\", \"(.*/account)(?:\\\\/.*?|\\\\?.*|$)(\\\\/.*?|$)(?:\\\\?.*|$)\")[$__rate_interval:])) by (endpoint) / sum(rate(label_replace(unchained_http_request_duration_seconds_count{namespace=\"$namespace\", coinstack=\"bitcoincash\", statusCode!=\"404\", route=~\"/api/v1/account.*\"}, \"endpoint\", \"$1$2\", \"route\", \"(.*/account)(?:\\\\/.*?|\\\\?.*|$)(\\\\/.*?|$)(?:\\\\?.*|$)\")[$__rate_interval:])) by (endpoint))",
       "legendFormat": "{{label_name}}"
      },
      {
       "expr": "(sum(rate(label_replace(unchained_http_request_duration_seconds_sum{namespace=\"$namespace\", coinstack=\"bitcoincash\", statusCode!=\"404\", route=~\"/api/v1/tx.*\"}, \"endpoint\", \"$1\", \"route\", \"(.*/tx).*\")[$__rate_interval:])) by (endpoint) / sum(rate(label_replace(unchained_http_request_duration_seconds_count{namespace=\"$namespace\", coinstack=\"bitcoincash\", statusCode!=\"404\", route=~\"/api/v1/tx.*\"}, \"endpoint\", \"$1\", \"route\", \"(.*/tx).*\")[$__rate_interval:])) by (endpoint))",
       "legendFormat": "{{label_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Cosmos",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 },
   "collapsed": true,
   "panels": [
    {
     "title": "WS Connection Count",
     "type": "stat",
     "gridPos": { "h": 12, "w": 3, "x": 0, "y": 82 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(unchained_ws_client_count{coinstack=\"cosmos\", namespace=\"$namespace\"})"
      }
     ]
    },
    {
     "type": "gauge",
     "gridPos": { "h": 7, "w": 9, "x": 3, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(kube_deployment_status_replicas_ready{namespace=\"$namespace\", deployment=~\"cosmos-api-.*\"} / kube_deployment_status_replicas{namespace=\"$namespace\", deployment=~\"cosmos-api-.*\"}) * 100",
       "legendFormat": "API"
      },
      {
       "expr": "(kube_statefulset_status_replicas_ready{namespace=\"$namespace\", statefulset=~\"cosmos-sts\"} / kube_statefulset_replicas{namespace=\"$namespace\", statefulset=~\"cosmos-sts\"}) * 100",
       "legendFormat": "STS"
      }
     ]
    },
    {
     "title": "Request Count",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(increase(label_replace(unchained_http_request_count{namespace=\"$namespace\", coinstack=\"cosmos\", statusCode!=\"404\", route=~\"/api/v1/(info|gas|send).*\"}, \"endpoint\", \"$1\", \"route\", \"(.*?)(?:\\\\?.*|$)\")[$__rate_interval:])) by (endpoint)",
       "legendFormat": "{{endpoint}}"
      },
      {
       "expr": "sum(increase(label_replace(unchained_http_request_count{namespace=\"$namespace\", coinstack=\"cosmos\", statusCode!=\"404\", route=~\"/api/v1/(account|validators).*\"}, \"endpoint\", \"$1$3\", \"route\", \"(.*/(account|validators))(?:\\\\/.*?|\\\\?.*|$)(\\\\/.*?|$)(?:\\\\?.*|$)\")[$__rate_interval:])) by (endpoint)",
       "legendFormat": "{{endpoint}}"
      },
      {
       "expr": "sum(increase(label_replace(unchained_http_request_count{namespace=\"$namespace\", coinstack=\"cosmos\", statusCode!=\"404\", route=~\"/api/v1/tx.*\"}, \"endpoint\", \"$1\", \"route\", \"(.*/tx).*\")[$__rate_interval:])) by (endpoint)",
       "legendFormat": "{{endpoint}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 5, "w": 9, "x": 3, "y": 89 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kube_deployment_status_replicas_ready{namespace=\"$namespace\", deployment=~\"cosmos-api-.*\"}",
       "legendFormat": "Available"
      },
      {
       "expr": "kube_deployment_status_replicas{namespace=\"$namespace\", deployment=~\"cosmos-api-.*\"}",
       "legendFormat": "Total"
      },
      {
       "expr": "kube_statefulset_status_replicas_ready{namespace=\"$namespace\", statefulset=\"cosmos-sts\"}",
       "legendFormat": "Available"
      },
      {
       "expr": "kube_statefulset_replicas{namespace=\"$namespace\", statefulset=\"cosmos-sts\"}",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Volume Space Usage",
     "type": "gauge",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 94 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max without(instance,node) (\n(\n  topk(1, kubelet_volume_stats_capacity_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$namespace\", persistentvolumeclaim=~\"data-daemon-cosmos-sts-0\"})\n  -\n  topk(1, kubelet_volume_stats_available_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$namespace\", persistentvolumeclaim=\"data-daemon-cosmos-sts-0\"})\n)\n/\ntopk(1, kubelet_volume_stats_capacity_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$namespace\", persistentvolumeclaim=\"data-daemon-cosmos-sts-0\"})\n* 100)\n",
       "legendFormat": "Daemon"
      }
     ]
    },
    {
     "title": "Average Request Duration",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 94 },
     "targets": [
      {
       "expr": "(sum(rate(label_replace(unchained_http_request_duration_seconds_sum{namespace=\"$namespace\", coinstack=\"cosmos\", statusCode!=\"404\", route=~\"/api/v1/(info|gas|send).*\"}, \"endpoint\", \"$1\", \"route\", \"(.*?)(?:\\\\?.*|$)\")[$__rate_interval:])) by (endpoint) / sum(rate(label_replace(unchained_http_request_duration_seconds_count{namespace=\"$namespace\", coinstack=\"cosmos\", statusCode!=\"404\", route=~\"/api/v1/(info|gas|send).*\"}, \"endpoint\", \"$1\", \"route\", \"(.*?)(?:\\\\?.*|$)\")[$__rate_interval:])) by (endpoint))",
       "legendFormat": "{{label_name}}"
      },
      {
       "expr": "(sum(rate(label_replace(unchained_http_request_duration_seconds_sum{namespace=\"$namespace\", coinstack=\"cosmos\", statusCode!=\"404\", route=~\"/api/v1/(account|validators).*\"}, \"endpoint\", \"$1$3\", \"route\", \"(.*/(account|validators))(?:\\\\/.*?|\\\\?.*|$)(\\\\/.*?|$)(?:\\\\?.*|$)\")[$__rate_interval:])) by (endpoint) / sum(rate(label_replace(unchained_http_request_duration_seconds_count{namespace=\"$namespace\", coinstack=\"cosmos\", statusCode!=\"404\", route=~\"/api/v1/(account|validators).*\"}, \"endpoint\", \"$1$3\", \"route\", \"(.*/(account|validators))(?:\\\\/.*?|\\\\?.*|$)(\\\\/.*?|$)(?:\\\\?.*|$)\")[$__rate_interval:])) by (endpoint))",
       "legendFormat": "{{label_name}}"
      },
      {
       "expr": "(sum(rate(label_replace(unchained_http_request_duration_seconds_sum{namespace=\"$namespace\", coinstack=\"cosmos\", statusCode!=\"404\", route=~\"/api/v1/tx.*\"}, \"endpoint\", \"$1\", \"route\", \"(.*/tx).*\")[$__rate_interval:])) by (endpoint) / sum(rate(label_replace(unchained_http_request_duration_seconds_count{namespace=\"$namespace\", coinstack=\"cosmos\", statusCode!=\"404\", route=~\"/api/v1/tx.*\"}, \"endpoint\", \"$1\", \"route\", \"(.*/tx).*\")[$__rate_interval:])) by (endpoint))",
       "legendFormat": "{{label_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Dogecoin",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 },
   "collapsed": true,
   "panels": [
    {
     "title": "WS Connection Count",
     "type": "stat",
     "gridPos": { "h": 12, "w": 3, "x": 0, "y": 59 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(unchained_ws_client_count{coinstack=\"dogecoin\", namespace=\"$namespace\"})"
      }
     ]
    },
    {
     "type": "gauge",
     "gridPos": { "h": 7, "w": 9, "x": 3, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(kube_deployment_status_replicas_ready{namespace=\"$namespace\", deployment=~\"dogecoin-api-.*\"} / kube_deployment_status_replicas{namespace=\"$namespace\", deployment=~\"dogecoin-api-.*\"}) * 100",
       "legendFormat": "API"
      },
      {
       "expr": "(kube_statefulset_status_replicas_ready{namespace=\"$namespace\", statefulset=~\"dogecoin-sts\"} / kube_statefulset_replicas{namespace=\"$namespace\", statefulset=~\"dogecoin-sts\"}) * 100",
       "legendFormat": "STS"
      }
     ]
    },
    {
     "title": "Request Count",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(increase(label_replace(unchained_http_request_count{namespace=\"$namespace\", coinstack=\"dogecoin\", statusCode!=\"404\", route=~\"/api/v1/(info|fees|send).*\"}, \"endpoint\", \"$1\", \"route\", \"(.*?)(?:\\\\?.*|$)\")[$__rate_interval:])) by (endpoint)",
       "legendFormat": "{{endpoint}}"
      },
      {
       "expr": "sum(increase(label_replace(unchained_http_request_count{namespace=\"$namespace\", coinstack=\"dogecoin\", statusCode!=\"404\", route=~\"/api/v1/account.*\"}, \"endpoint\", \"$1$2\", \"route\", \"(.*/account)(?:\\\\/.*?|\\\\?.*|$)(\\\\/.*?|$)(?:\\\\?.*|$)\")[$__rate_interval:])) by (endpoint)",
       "legendFormat": "{{endpoint}}"
      },
      {
       "expr": "sum(increase(label_replace(unchained_http_request_count{namespace=\"$namespace\", coinstack=\"dogecoin\", statusCode!=\"404\", route=~\"/api/v1/tx.*\"}, \"endpoint\", \"$1\", \"route\", \"(.*/tx).*\")[$__rate_interval:])) by (endpoint)",
       "legendFormat": "{{endpoint}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 5, "w": 9, "x": 3, "y": 66 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kube_deployment_status_replicas_ready{namespace=\"$namespace\", deployment=~\"dogecoin-api-.*\"}",
       "legendFormat": "Available"
      },
      {
       "expr": "kube_deployment_status_replicas{namespace=\"$namespace\", deployment=~\"dogecoin-api-.*\"}",
       "legendFormat": "Total"
      },
      {
       "expr": "kube_statefulset_status_replicas_ready{namespace=\"$namespace\", statefulset=\"dogecoin-sts\"}",
       "legendFormat": "Available"
      },
      {
       "expr": "kube_statefulset_replicas{namespace=\"$namespace\", statefulset=\"dogecoin-sts\"}",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Volume Space Usage",
     "type": "gauge",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max without(instance,node) (\n(\n  topk(1, kubelet_volume_stats_capacity_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$namespace\", persistentvolumeclaim=~\"data-daemon-dogecoin-sts-0\"})\n  -\n  topk(1, kubelet_volume_stats_available_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$namespace\", persistentvolumeclaim=\"data-daemon-dogecoin-sts-0\"})\n)\n/\ntopk(1, kubelet_volume_stats_capacity_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$namespace\", persistentvolumeclaim=\"data-daemon-dogecoin-sts-0\"})\n* 100)\n",
       "legendFormat": "Daemon"
      },
      {
       "expr": "max without(instance,node) (\n(\n  topk(1, kubelet_volume_stats_capacity_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$namespace\", persistentvolumeclaim=\"data-indexer-dogecoin-sts-0\"})\n  -\n  topk(1, kubelet_volume_stats_available_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$namespace\", persistentvolumeclaim=\"data-indexer-dogecoin-sts-0\"})\n)\n/\ntopk(1, kubelet_volume_stats_capacity_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$namespace\", persistentvolumeclaim=\"data-indexer-dogecoin-sts-0\"})\n* 100)",
       "legendFormat": "Indexer"
      }
     ]
    },
    {
     "title": "Average Request Duration",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 71 },
     "targets": [
      {
       "expr": "(sum(rate(label_replace(unchained_http_request_duration_seconds_sum{namespace=\"$namespace\", coinstack=\"dogecoin\", statusCode!=\"404\", route=~\"/api/v1/(info|fees|send).*\"}, \"endpoint\", \"$1\", \"route\", \"(.*?)(?:\\\\?.*|$)\")[$__rate_interval:])) by (endpoint) / sum(rate(label_replace(unchained_http_request_duration_seconds_count{namespace=\"$namespace\", coinstack=\"dogecoin\", statusCode!=\"404\", route=~\"/api/v1/(info|fees|send).*\"}, \"endpoint\", \"$1\", \"route\", \"(.*?)(?:\\\\?.*|$)\")[$__rate_interval:])) by (endpoint))",
       "legendFormat": "{{label_name}}"
      },
      {
       "expr": "(sum(rate(label_replace(unchained_http_request_duration_seconds_sum{namespace=\"$namespace\", coinstack=\"dogecoin\", statusCode!=\"404\", route=~\"/api/v1/account.*\"}, \"endpoint\", \"$1$2\", \"route\", \"(.*/account)(?:\\\\/.*?|\\\\?.*|$)(\\\\/.*?|$)(?:\\\\?.*|$)\")[$__rate_interval:])) by (endpoint) / sum(rate(label_replace(unchained_http_request_duration_seconds_count{namespace=\"$namespace\", coinstack=\"dogecoin\", statusCode!=\"404\", route=~\"/api/v1/account.*\"}, \"endpoint\", \"$1$2\", \"route\", \"(.*/account)(?:\\\\/.*?|\\\\?.*|$)(\\\\/.*?|$)(?:\\\\?.*|$)\")[$__rate_interval:])) by (endpoint))",
       "legendFormat": "{{label_name}}"
      },
      {
       "expr": "(sum(rate(label_replace(unchained_http_request_duration_seconds_sum{namespace=\"$namespace\", coinstack=\"dogecoin\", statusCode!=\"404\", route=~\"/api/v1/tx.*\"}, \"endpoint\", \"$1\", \"route\", \"(.*/tx).*\")[$__rate_interval:])) by (endpoint) / sum(rate(label_replace(unchained_http_request_duration_seconds_count{namespace=\"$namespace\", coinstack=\"dogecoin\", statusCode!=\"404\", route=~\"/api/v1/tx.*\"}, \"endpoint\", \"$1\", \"route\", \"(.*/tx).*\")[$__rate_interval:])) by (endpoint))",
       "legendFormat": "{{label_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Ethereum",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 },
   "collapsed": true,
   "panels": [
    {
     "title": "WS Connection Count",
     "type": "stat",
     "gridPos": { "h": 12, "w": 3, "x": 0, "y": 60 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(unchained_ws_client_count{coinstack=\"bnbsmartchain\", namespace=\"$namespace\"})"
      }
     ]
    },
    {
     "type": "gauge",
     "gridPos": { "h": 7, "w": 9, "x": 3, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(kube_deployment_status_replicas_ready{namespace=\"$namespace\", deployment=~\"ethereum-api-.*\"} / kube_deployment_status_replicas{namespace=\"$namespace\", deployment=~\"ethereum-api-.*\"}) * 100",
       "legendFormat": "API"
      },
      {
       "expr": "(kube_statefulset_status_replicas_ready{namespace=\"$namespace\", statefulset=~\"ethereum-sts\"} / kube_statefulset_replicas{namespace=\"$namespace\", statefulset=~\"ethereum-sts\"}) * 100",
       "legendFormat": "STS"
      }
     ]
    },
    {
     "title": "Request Count",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(increase(label_replace(unchained_http_request_count{namespace=\"$namespace\", coinstack=\"ethereum\", statusCode!=\"404\", route=~\"/api/v1/(info|gas|send|metadata).*\"}, \"endpoint\", \"$1$2\", \"route\", \"(.*?)(?:\\\\?.*|$)\")[$__rate_interval:])) by (endpoint)",
       "legendFormat": "{{endpoint}}"
      },
      {
       "expr": "sum(increase(label_replace(unchained_http_request_count{namespace=\"$namespace\", coinstack=\"ethereum\", statusCode!=\"404\", route=~\"/api/v1/account.*\"}, \"endpoint\", \"$1$2\", \"route\", \"(.*/account)(?:\\\\/.*?|\\\\?.*|$)(\\\\/.*?|$)(?:\\\\?.*|$)\")[$__rate_interval:])) by (endpoint)",
       "legendFormat": "{{endpoint}}"
      },
      {
       "expr": "sum(increase(label_replace(unchained_http_request_count{namespace=\"$namespace\", coinstack=\"ethereum\", statusCode!=\"404\", route=~\"/api/v1/tx.*\"}, \"endpoint\", \"$1\", \"route\", \"(.*/tx).*\")[$__rate_interval:])) by (endpoint)",
       "legendFormat": "{{endpoint}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 5, "w": 9, "x": 3, "y": 67 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kube_deployment_status_replicas_ready{namespace=\"$namespace\", deployment=~\"ethereum-api-.*\"}",
       "legendFormat": "Available"
      },
      {
       "expr": "kube_deployment_status_replicas{namespace=\"$namespace\", deployment=~\"ethereum-api-.*\"}",
       "legendFormat": "Total"
      },
      {
       "expr": "kube_statefulset_status_replicas_ready{namespace=\"$namespace\", statefulset=\"ethereum-sts\"}",
       "legendFormat": "Available"
      },
      {
       "expr": "kube_statefulset_replicas{namespace=\"$namespace\", statefulset=\"ethereum-sts\"}",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Volume Space Usage",
     "type": "gauge",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max without(instance,node) (\n(\n  topk(1, kubelet_volume_stats_capacity_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$namespace\", persistentvolumeclaim=~\"data-daemon-ethereum-sts-0\"})\n  -\n  topk(1, kubelet_volume_stats_available_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$namespace\", persistentvolumeclaim=\"data-daemon-ethereum-sts-0\"})\n)\n/\ntopk(1, kubelet_volume_stats_capacity_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$namespace\", persistentvolumeclaim=\"data-daemon-ethereum-sts-0\"})\n* 100)\n",
       "legendFormat": "Daemon"
      },
      {
       "expr": "max without(instance,node) (\n(\n  topk(1, kubelet_volume_stats_capacity_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$namespace\", persistentvolumeclaim=\"data-indexer-ethereum-sts-0\"})\n  -\n  topk(1, kubelet_volume_stats_available_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$namespace\", persistentvolumeclaim=\"data-indexer-ethereum-sts-0\"})\n)\n/\ntopk(1, kubelet_volume_stats_capacity_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$namespace\", persistentvolumeclaim=\"data-indexer-ethereum-sts-0\"})\n* 100)",
       "legendFormat": "Indexer"
      },
      {
       "expr": "max without(instance,node) (\n(\n  topk(1, kubelet_volume_stats_capacity_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$namespace\", persistentvolumeclaim=\"data-daemon-beacon-ethereum-sts-0\"})\n  -\n  topk(1, kubelet_volume_stats_available_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$namespace\", persistentvolumeclaim=\"data-daemon-beacon-ethereum-sts-0\"})\n)\n/\ntopk(1, kubelet_volume_stats_capacity_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$namespace\", persistentvolumeclaim=\"data-daemon-beacon-ethereum-sts-0\"})\n* 100)",
       "legendFormat": "Consensus"
      }
     ]
    },
    {
     "title": "Average Request Duration",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 72 },
     "targets": [
      {
       "expr": "(sum(rate(label_replace(unchained_http_request_duration_seconds_sum{namespace=\"$namespace\", coinstack=\"ethereum\", statusCode!=\"404\", route=~\"/api/v1/(info|gas|send|metadata).*\"}, \"endpoint\", \"$1$2\", \"route\", \"(.*?)(?:\\\\?.*|$)\")[$__rate_interval:])) by (endpoint) / sum(rate(label_replace(unchained_http_request_duration_seconds_count{namespace=\"$namespace\", coinstack=\"ethereum\", statusCode!=\"404\", route=~\"/api/v1/(info|gas|send|metadata).*\"}, \"endpoint\", \"$1$2\", \"route\", \"(.*?)(?:\\\\?.*|$)\")[$__rate_interval:])) by (endpoint))",
       "legendFormat": "{{label_name}}"
      },
      {
       "expr": "(sum(rate(label_replace(unchained_http_request_duration_seconds_sum{namespace=\"$namespace\", coinstack=\"ethereum\", statusCode!=\"404\", route=~\"/api/v1/account.*\"}, \"endpoint\", \"$1$2\", \"route\", \"(.*/account)(?:\\\\/.*?|\\\\?.*|$)(\\\\/.*?|$)(?:\\\\?.*|$)\")[$__rate_interval:])) by (endpoint) / sum(rate(label_replace(unchained_http_request_duration_seconds_count{namespace=\"$namespace\", coinstack=\"ethereum\", statusCode!=\"404\", route=~\"/api/v1/account.*\"}, \"endpoint\", \"$1$2\", \"route\", \"(.*/account)(?:\\\\/.*?|\\\\?.*|$)(\\\\/.*?|$)(?:\\\\?.*|$)\")[$__rate_interval:])) by (endpoint))",
       "legendFormat": "{{label_name}}"
      },
      {
       "expr": "(sum(rate(label_replace(unchained_http_request_duration_seconds_sum{namespace=\"$namespace\", coinstack=\"ethereum\", statusCode!=\"404\", route=~\"/api/v1/tx.*\"}, \"endpoint\", \"$1\", \"route\", \"(.*/tx).*\")[$__rate_interval:])) by (endpoint) / sum(rate(label_replace(unchained_http_request_duration_seconds_count{namespace=\"$namespace\", coinstack=\"ethereum\", statusCode!=\"404\", route=~\"/api/v1/tx.*\"}, \"endpoint\", \"$1\", \"route\", \"(.*/tx).*\")[$__rate_interval:])) by (endpoint))",
       "legendFormat": "{{label_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Gnosis",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 },
   "collapsed": true,
   "panels": [
    {
     "title": "WS Connection Count",
     "type": "stat",
     "gridPos": { "h": 12, "w": 3, "x": 0, "y": 61 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(unchained_ws_client_count{coinstack=\"gnosis\", namespace=\"$namespace\"})"
      }
     ]
    },
    {
     "type": "gauge",
     "gridPos": { "h": 7, "w": 9, "x": 3, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(kube_deployment_status_replicas_ready{namespace=\"$namespace\", deployment=~\"gnosis-api-.*\"} / kube_deployment_status_replicas{namespace=\"$namespace\", deployment=~\"gnosis-api-.*\"}) * 100",
       "legendFormat": "API"
      },
      {
       "expr": "(kube_statefulset_status_replicas_ready{namespace=\"$namespace\", statefulset=~\"gnosis-sts\"} / kube_statefulset_replicas{namespace=\"$namespace\", statefulset=~\"gnosis-sts\"}) * 100",
       "legendFormat": "STS"
      }
     ]
    },
    {
     "title": "Request Count",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(increase(label_replace(unchained_http_request_count{namespace=\"$namespace\", coinstack=\"gnosis\", statusCode!=\"404\", route=~\"/api/v1/(info|gas|send|metadata).*\"}, \"endpoint\", \"$1$2\", \"route\", \"(.*?)(?:\\\\?.*|$)\")[$__rate_interval:])) by (endpoint)",
       "legendFormat": "{{endpoint}}"
      },
      {
       "expr": "sum(increase(label_replace(unchained_http_request_count{namespace=\"$namespace\", coinstack=\"gnosis\", statusCode!=\"404\", route=~\"/api/v1/account.*\"}, \"endpoint\", \"$1$2\", \"route\", \"(.*/account)(?:\\\\/.*?|\\\\?.*|$)(\\\\/.*?|$)(?:\\\\?.*|$)\")[$__rate_interval:])) by (endpoint)",
       "legendFormat": "{{endpoint}}"
      },
      {
       "expr": "sum(increase(label_replace(unchained_http_request_count{namespace=\"$namespace\", coinstack=\"gnosis\", statusCode!=\"404\", route=~\"/api/v1/tx.*\"}, \"endpoint\", \"$1\", \"route\", \"(.*/tx).*\")[$__rate_interval:])) by (endpoint)",
       "legendFormat": "{{endpoint}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 5, "w": 9, "x": 3, "y": 68 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kube_deployment_status_replicas_ready{namespace=\"$namespace\", deployment=~\"gnosis-api-.*\"}",
       "legendFormat": "Available"
      },
      {
       "expr": "kube_deployment_status_replicas{namespace=\"$namespace\", deployment=~\"gnosis-api-.*\"}",
       "legendFormat": "Total"
      },
      {
       "expr": "kube_statefulset_status_replicas_ready{namespace=\"$namespace\", statefulset=\"gnosis-sts\"}",
       "legendFormat": "Available"
      },
      {
       "expr": "kube_statefulset_replicas{namespace=\"$namespace\", statefulset=\"gnosis-sts\"}",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Volume Space Usage",
     "type": "gauge",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max without(instance,node) (\n(\n  topk(1, kubelet_volume_stats_capacity_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$namespace\", persistentvolumeclaim=~\"data-daemon-gnosis-sts-0\"})\n  -\n  topk(1, kubelet_volume_stats_available_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$namespace\", persistentvolumeclaim=\"data-daemon-gnosis-sts-0\"})\n)\n/\ntopk(1, kubelet_volume_stats_capacity_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$namespace\", persistentvolumeclaim=\"data-daemon-gnosis-sts-0\"})\n* 100)\n",
       "legendFormat": "Daemon"
      },
      {
       "expr": "max without(instance,node) (\n(\n  topk(1, kubelet_volume_stats_capacity_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$namespace\", persistentvolumeclaim=\"data-indexer-gnosis-sts-0\"})\n  -\n  topk(1, kubelet_volume_stats_available_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$namespace\", persistentvolumeclaim=\"data-indexer-gnosis-sts-0\"})\n)\n/\ntopk(1, kubelet_volume_stats_capacity_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$namespace\", persistentvolumeclaim=\"data-indexer-gnosis-sts-0\"})\n* 100)",
       "legendFormat": "Indexer"
      },
      {
       "expr": "max without(instance,node) (\n(\n  topk(1, kubelet_volume_stats_capacity_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$namespace\", persistentvolumeclaim=\"data-daemon-beacon-gnosis-sts-0\"})\n  -\n  topk(1, kubelet_volume_stats_available_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$namespace\", persistentvolumeclaim=\"data-daemon-beacon-gnosis-sts-0\"})\n)\n/\ntopk(1, kubelet_volume_stats_capacity_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$namespace\", persistentvolumeclaim=\"data-daemon-beacon-gnosis-sts-0\"})\n* 100)",
       "legendFormat": "Beacon"
      }
     ]
    },
    {
     "title": "Average Request Duration",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 73 },
     "targets": [
      {
       "expr": "(sum(rate(label_replace(unchained_http_request_duration_seconds_sum{namespace=\"$namespace\", coinstack=\"gnosis\", statusCode!=\"404\", route=~\"/api/v1/(info|gas|send|metadata).*\"}, \"endpoint\", \"$1$2\", \"route\", \"(.*?)(?:\\\\?.*|$)\")[$__rate_interval:])) by (endpoint) / sum(rate(label_replace(unchained_http_request_duration_seconds_count{namespace=\"$namespace\", coinstack=\"gnosis\", statusCode!=\"404\", route=~\"/api/v1/(info|gas|send|metadata).*\"}, \"endpoint\", \"$1$2\", \"route\", \"(.*?)(?:\\\\?.*|$)\")[$__rate_interval:])) by (endpoint))",
       "legendFormat": "{{label_name}}"
      },
      {
       "expr": "(sum(rate(label_replace(unchained_http_request_duration_seconds_sum{namespace=\"$namespace\", coinstack=\"gnosis\", statusCode!=\"404\", route=~\"/api/v1/account.*\"}, \"endpoint\", \"$1$2\", \"route\", \"(.*/account)(?:\\\\/.*?|\\\\?.*|$)(\\\\/.*?|$)(?:\\\\?.*|$)\")[$__rate_interval:])) by (endpoint) / sum(rate(label_replace(unchained_http_request_duration_seconds_count{namespace=\"$namespace\", coinstack=\"gnosis\", statusCode!=\"404\", route=~\"/api/v1/account.*\"}, \"endpoint\", \"$1$2\", \"route\", \"(.*/account)(?:\\\\/.*?|\\\\?.*|$)(\\\\/.*?|$)(?:\\\\?.*|$)\")[$__rate_interval:])) by (endpoint))",
       "legendFormat": "{{label_name}}"
      },
      {
       "expr": "(sum(rate(label_replace(unchained_http_request_duration_seconds_sum{namespace=\"$namespace\", coinstack=\"gnosis\", statusCode!=\"404\", route=~\"/api/v1/tx.*\"}, \"endpoint\", \"$1\", \"route\", \"(.*/tx).*\")[$__rate_interval:])) by (endpoint) / sum(rate(label_replace(unchained_http_request_duration_seconds_count{namespace=\"$namespace\", coinstack=\"gnosis\", statusCode!=\"404\", route=~\"/api/v1/tx.*\"}, \"endpoint\", \"$1\", \"route\", \"(.*/tx).*\")[$__rate_interval:])) by (endpoint))",
       "legendFormat": "{{label_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Litecoin",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 },
   "collapsed": true,
   "panels": [
    {
     "title": "WS Connection Count",
     "type": "stat",
     "gridPos": { "h": 12, "w": 3, "x": 0, "y": 86 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(unchained_ws_client_count{coinstack=\"litecoin\", namespace=\"$namespace\"})"
      }
     ]
    },
    {
     "type": "gauge",
     "gridPos": { "h": 7, "w": 9, "x": 3, "y": 86 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(kube_deployment_status_replicas_ready{namespace=\"$namespace\", deployment=~\"litecoin-api-.*\"} / kube_deployment_status_replicas{namespace=\"$namespace\", deployment=~\"litecoin-api-.*\"}) * 100",
       "legendFormat": "API"
      },
      {
       "expr": "(kube_statefulset_status_replicas_ready{namespace=\"$namespace\", statefulset=~\"litecoin-sts\"} / kube_statefulset_replicas{namespace=\"$namespace\", statefulset=~\"litecoin-sts\"}) * 100",
       "legendFormat": "STS"
      }
     ]
    },
    {
     "title": "Request Count",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 86 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(increase(label_replace(unchained_http_request_count{namespace=\"$namespace\", coinstack=\"litecoin\", statusCode!=\"404\", route=~\"/api/v1/(info|fees|send).*\"}, \"endpoint\", \"$1\", \"route\", \"(.*?)(?:\\\\?.*|$)\")[$__rate_interval:])) by (endpoint)",
       "legendFormat": "{{endpoint}}"
      },
      {
       "expr": "sum(increase(label_replace(unchained_http_request_count{namespace=\"$namespace\", coinstack=\"litecoin\", statusCode!=\"404\", route=~\"/api/v1/account.*\"}, \"endpoint\", \"$1$2\", \"route\", \"(.*/account)(?:\\\\/.*?|\\\\?.*|$)(\\\\/.*?|$)(?:\\\\?.*|$)\")[$__rate_interval:])) by (endpoint)",
       "legendFormat": "{{endpoint}}"
      },
      {
       "expr": "sum(increase(label_replace(unchained_http_request_count{namespace=\"$namespace\", coinstack=\"litecoin\", statusCode!=\"404\", route=~\"/api/v1/tx.*\"}, \"endpoint\", \"$1\", \"route\", \"(.*/tx).*\")[$__rate_interval:])) by (endpoint)",
       "legendFormat": "{{endpoint}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 5, "w": 9, "x": 3, "y": 93 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kube_deployment_status_replicas_ready{namespace=\"$namespace\", deployment=~\"litecoin-api-.*\"}",
       "legendFormat": "Available"
      },
      {
       "expr": "kube_deployment_status_replicas{namespace=\"$namespace\", deployment=~\"litecoin-api-.*\"}",
       "legendFormat": "Total"
      },
      {
       "expr": "kube_statefulset_status_replicas_ready{namespace=\"$namespace\", statefulset=\"litecoin-sts\"}",
       "legendFormat": "Available"
      },
      {
       "expr": "kube_statefulset_replicas{namespace=\"$namespace\", statefulset=\"litecoin-sts\"}",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Volume Space Usage",
     "type": "gauge",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 98 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max without(instance,node) (\n(\n  topk(1, kubelet_volume_stats_capacity_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$namespace\", persistentvolumeclaim=~\"data-daemon-litecoin-sts-0\"})\n  -\n  topk(1, kubelet_volume_stats_available_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$namespace\", persistentvolumeclaim=\"data-daemon-litecoin-sts-0\"})\n)\n/\ntopk(1, kubelet_volume_stats_capacity_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$namespace\", persistentvolumeclaim=\"data-daemon-litecoin-sts-0\"})\n* 100)\n",
       "legendFormat": "Daemon"
      },
      {
       "expr": "max without(instance,node) (\n(\n  topk(1, kubelet_volume_stats_capacity_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$namespace\", persistentvolumeclaim=\"data-indexer-litecoin-sts-0\"})\n  -\n  topk(1, kubelet_volume_stats_available_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$namespace\", persistentvolumeclaim=\"data-indexer-litecoin-sts-0\"})\n)\n/\ntopk(1, kubelet_volume_stats_capacity_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$namespace\", persistentvolumeclaim=\"data-indexer-litecoin-sts-0\"})\n* 100)",
       "legendFormat": "Indexer"
      }
     ]
    },
    {
     "title": "Average Request Duration",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 98 },
     "targets": [
      {
       "expr": "(sum(rate(label_replace(unchained_http_request_duration_seconds_sum{namespace=\"$namespace\", coinstack=\"litecoin\", statusCode!=\"404\", route=~\"/api/v1/(info|fees|send).*\"}, \"endpoint\", \"$1\", \"route\", \"(.*?)(?:\\\\?.*|$)\")[$__rate_interval:])) by (endpoint) / sum(rate(label_replace(unchained_http_request_duration_seconds_count{namespace=\"$namespace\", coinstack=\"litecoin\", statusCode!=\"404\", route=~\"/api/v1/(info|fees|send).*\"}, \"endpoint\", \"$1\", \"route\", \"(.*?)(?:\\\\?.*|$)\")[$__rate_interval:])) by (endpoint))",
       "legendFormat": "{{label_name}}"
      },
      {
       "expr": "(sum(rate(label_replace(unchained_http_request_duration_seconds_sum{namespace=\"$namespace\", coinstack=\"litecoin\", statusCode!=\"404\", route=~\"/api/v1/account.*\"}, \"endpoint\", \"$1$2\", \"route\", \"(.*/account)(?:\\\\/.*?|\\\\?.*|$)(\\\\/.*?|$)(?:\\\\?.*|$)\")[$__rate_interval:])) by (endpoint) / sum(rate(label_replace(unchained_http_request_duration_seconds_count{namespace=\"$namespace\", coinstack=\"litecoin\", statusCode!=\"404\", route=~\"/api/v1/account.*\"}, \"endpoint\", \"$1$2\", \"route\", \"(.*/account)(?:\\\\/.*?|\\\\?.*|$)(\\\\/.*?|$)(?:\\\\?.*|$)\")[$__rate_interval:])) by (endpoint))",
       "legendFormat": "{{label_name}}"
      },
      {
       "expr": "(sum(rate(label_replace(unchained_http_request_duration_seconds_sum{namespace=\"$namespace\", coinstack=\"litecoin\", statusCode!=\"404\", route=~\"/api/v1/tx.*\"}, \"endpoint\", \"$1\", \"route\", \"(.*/tx).*\")[$__rate_interval:])) by (endpoint) / sum(rate(label_replace(unchained_http_request_duration_seconds_count{namespace=\"$namespace\", coinstack=\"litecoin\", statusCode!=\"404\", route=~\"/api/v1/tx.*\"}, \"endpoint\", \"$1\", \"route\", \"(.*/tx).*\")[$__rate_interval:])) by (endpoint))",
       "legendFormat": "{{label_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Optimism",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 },
   "collapsed": true,
   "panels": [
    {
     "title": "WS Connection Count",
     "type": "stat",
     "gridPos": { "h": 12, "w": 3, "x": 0, "y": 63 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(unchained_ws_client_count{coinstack=\"gnosis\", namespace=\"$namespace\"})"
      }
     ]
    },
    {
     "type": "gauge",
     "gridPos": { "h": 7, "w": 9, "x": 3, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(kube_deployment_status_replicas_ready{namespace=\"$namespace\", deployment=~\"optimism-api-.*\"} / kube_deployment_status_replicas{namespace=\"$namespace\", deployment=~\"optimism-api-.*\"}) * 100",
       "legendFormat": "API"
      },
      {
       "expr": "(kube_statefulset_status_replicas_ready{namespace=\"$namespace\", statefulset=~\"optimism-sts\"} / kube_statefulset_replicas{namespace=\"$namespace\", statefulset=~\"optimism-sts\"}) * 100",
       "legendFormat": "STS"
      }
     ]
    },
    {
     "title": "Request Count",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(increase(label_replace(unchained_http_request_count{namespace=\"$namespace\", coinstack=\"optimism\", statusCode!=\"404\", route=~\"/api/v1/(info|gas|send|metadata).*\"}, \"endpoint\", \"$1$2\", \"route\", \"(.*?)(?:\\\\?.*|$)\")[$__rate_interval:])) by (endpoint)",
       "legendFormat": "{{endpoint}}"
      },
      {
       "expr": "sum(increase(label_replace(unchained_http_request_count{namespace=\"$namespace\", coinstack=\"optimism\", statusCode!=\"404\", route=~\"/api/v1/account.*\"}, \"endpoint\", \"$1$2\", \"route\", \"(.*/account)(?:\\\\/.*?|\\\\?.*|$)(\\\\/.*?|$)(?:\\\\?.*|$)\")[$__rate_interval:])) by (endpoint)",
       "legendFormat": "{{endpoint}}"
      },
      {
       "expr": "sum(increase(label_replace(unchained_http_request_count{namespace=\"$namespace\", coinstack=\"optimism\", statusCode!=\"404\", route=~\"/api/v1/tx.*\"}, \"endpoint\", \"$1\", \"route\", \"(.*/tx).*\")[$__rate_interval:])) by (endpoint)",
       "legendFormat": "{{endpoint}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 5, "w": 9, "x": 3, "y": 70 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kube_deployment_status_replicas_ready{namespace=\"$namespace\", deployment=~\"optimism-api-.*\"}",
       "legendFormat": "Available"
      },
      {
       "expr": "kube_deployment_status_replicas{namespace=\"$namespace\", deployment=~\"optimism-api-.*\"}",
       "legendFormat": "Total"
      },
      {
       "expr": "kube_statefulset_status_replicas_ready{namespace=\"$namespace\", statefulset=\"optimism-sts\"}",
       "legendFormat": "Available"
      },
      {
       "expr": "kube_statefulset_replicas{namespace=\"$namespace\", statefulset=\"optimism-sts\"}",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Volume Space Usage",
     "type": "gauge",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max without(instance,node) (\n(\n  topk(1, kubelet_volume_stats_capacity_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$namespace\", persistentvolumeclaim=~\"data-daemon-optimism-sts-0\"})\n  -\n  topk(1, kubelet_volume_stats_available_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$namespace\", persistentvolumeclaim=\"data-daemon-optimism-sts-0\"})\n)\n/\ntopk(1, kubelet_volume_stats_capacity_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$namespace\", persistentvolumeclaim=\"data-daemon-optimism-sts-0\"})\n* 100)\n",
       "legendFormat": "Daemon"
      },
      {
       "expr": "max without(instance,node) (\n(\n  topk(1, kubelet_volume_stats_capacity_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$namespace\", persistentvolumeclaim=\"data-indexer-optimism-sts-0\"})\n  -\n  topk(1, kubelet_volume_stats_available_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$namespace\", persistentvolumeclaim=\"data-indexer-optimism-sts-0\"})\n)\n/\ntopk(1, kubelet_volume_stats_capacity_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$namespace\", persistentvolumeclaim=\"data-indexer-optimism-sts-0\"})\n* 100)",
       "legendFormat": "Indexer"
      },
      {
       "expr": "max without(instance,node) (\n(\n  topk(1, kubelet_volume_stats_capacity_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$namespace\", persistentvolumeclaim=\"data-op-node-optimism-sts-0\"})\n  -\n  topk(1, kubelet_volume_stats_available_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$namespace\", persistentvolumeclaim=\"data-op-node-optimism-sts-0\"})\n)\n/\ntopk(1, kubelet_volume_stats_capacity_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$namespace\", persistentvolumeclaim=\"data-op-node-optimism-sts-0\"})\n* 100)",
       "legendFormat": "Op Node"
      }
     ]
    },
    {
     "title": "Average Request Duration",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 75 },
     "targets": [
      {
       "expr": "(sum(rate(label_replace(unchained_http_request_duration_seconds_sum{namespace=\"$namespace\", coinstack=\"optimism\", statusCode!=\"404\", route=~\"/api/v1/(info|gas|send|metadata).*\"}, \"endpoint\", \"$1$2\", \"route\", \"(.*?)(?:\\\\?.*|$)\")[$__rate_interval:])) by (endpoint) / sum(rate(label_replace(unchained_http_request_duration_seconds_count{namespace=\"$namespace\", coinstack=\"optimism\", statusCode!=\"404\", route=~\"/api/v1/(info|gas|send|metadata).*\"}, \"endpoint\", \"$1$2\", \"route\", \"(.*?)(?:\\\\?.*|$)\")[$__rate_interval:])) by (endpoint))",
       "legendFormat": "{{label_name}}"
      },
      {
       "expr": "(sum(rate(label_replace(unchained_http_request_duration_seconds_sum{namespace=\"$namespace\", coinstack=\"optimism\", statusCode!=\"404\", route=~\"/api/v1/account.*\"}, \"endpoint\", \"$1$2\", \"route\", \"(.*/account)(?:\\\\/.*?|\\\\?.*|$)(\\\\/.*?|$)(?:\\\\?.*|$)\")[$__rate_interval:])) by (endpoint) / sum(rate(label_replace(unchained_http_request_duration_seconds_count{namespace=\"$namespace\", coinstack=\"optimism\", statusCode!=\"404\", route=~\"/api/v1/account.*\"}, \"endpoint\", \"$1$2\", \"route\", \"(.*/account)(?:\\\\/.*?|\\\\?.*|$)(\\\\/.*?|$)(?:\\\\?.*|$)\")[$__rate_interval:])) by (endpoint))",
       "legendFormat": "{{label_name}}"
      },
      {
       "expr": "(sum(rate(label_replace(unchained_http_request_duration_seconds_sum{namespace=\"$namespace\", coinstack=\"optimism\", statusCode!=\"404\", route=~\"/api/v1/tx.*\"}, \"endpoint\", \"$1\", \"route\", \"(.*/tx).*\")[$__rate_interval:])) by (endpoint) / sum(rate(label_replace(unchained_http_request_duration_seconds_count{namespace=\"$namespace\", coinstack=\"optimism\", statusCode!=\"404\", route=~\"/api/v1/tx.*\"}, \"endpoint\", \"$1\", \"route\", \"(.*/tx).*\")[$__rate_interval:])) by (endpoint))",
       "legendFormat": "{{label_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Polygon",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 },
   "collapsed": true,
   "panels": [
    {
     "title": "WS Connection Count",
     "type": "stat",
     "gridPos": { "h": 12, "w": 3, "x": 0, "y": 89 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(unchained_ws_client_count{coinstack=\"polygon\", namespace=\"$namespace\"})"
      }
     ]
    },
    {
     "type": "gauge",
     "gridPos": { "h": 7, "w": 9, "x": 3, "y": 89 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(kube_deployment_status_replicas_ready{namespace=\"$namespace\", deployment=~\"polygon-api-.*\"} / kube_deployment_status_replicas{namespace=\"$namespace\", deployment=~\"polygon-api-.*\"}) * 100",
       "legendFormat": "API"
      },
      {
       "expr": "(kube_statefulset_status_replicas_ready{namespace=\"$namespace\", statefulset=~\"polygon-sts\"} / kube_statefulset_replicas{namespace=\"$namespace\", statefulset=~\"polygon-sts\"}) * 100",
       "legendFormat": "STS"
      }
     ]
    },
    {
     "title": "Request Count",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 89 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(increase(label_replace(unchained_http_request_count{namespace=\"$namespace\", coinstack=\"polygon\", statusCode!=\"404\", route=~\"/api/v1/(info|gas|send|metadata).*\"}, \"endpoint\", \"$1$2\", \"route\", \"(.*?)(?:\\\\?.*|$)\")[$__rate_interval:])) by (endpoint)",
       "legendFormat": "{{endpoint}}"
      },
      {
       "expr": "sum(increase(label_replace(unchained_http_request_count{namespace=\"$namespace\", coinstack=\"polygon\", statusCode!=\"404\", route=~\"/api/v1/account.*\"}, \"endpoint\", \"$1$2\", \"route\", \"(.*/account)(?:\\\\/.*?|\\\\?.*|$)(\\\\/.*?|$)(?:\\\\?.*|$)\")[$__rate_interval:])) by (endpoint)",
       "legendFormat": "{{endpoint}}"
      },
      {
       "expr": "sum(increase(label_replace(unchained_http_request_count{namespace=\"$namespace\", coinstack=\"polygon\", statusCode!=\"404\", route=~\"/api/v1/tx.*\"}, \"endpoint\", \"$1\", \"route\", \"(.*/tx).*\")[$__rate_interval:])) by (endpoint)",
       "legendFormat": "{{endpoint}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 5, "w": 9, "x": 3, "y": 96 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kube_deployment_status_replicas_ready{namespace=\"$namespace\", deployment=~\"polygon-api-.*\"}",
       "legendFormat": "Available"
      },
      {
       "expr": "kube_deployment_status_replicas{namespace=\"$namespace\", deployment=~\"polygon-api-.*\"}",
       "legendFormat": "Total"
      },
      {
       "expr": "kube_statefulset_status_replicas_ready{namespace=\"$namespace\", statefulset=\"polygon-sts\"}",
       "legendFormat": "Available"
      },
      {
       "expr": "kube_statefulset_replicas{namespace=\"$namespace\", statefulset=\"polygon-sts\"}",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Volume Space Usage",
     "type": "gauge",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 101 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max without(instance,node) (\n(\n  topk(1, kubelet_volume_stats_capacity_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$namespace\", persistentvolumeclaim=~\"data-daemon-polygon-sts-0\"})\n  -\n  topk(1, kubelet_volume_stats_available_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$namespace\", persistentvolumeclaim=\"data-daemon-polygon-sts-0\"})\n)\n/\ntopk(1, kubelet_volume_stats_capacity_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$namespace\", persistentvolumeclaim=\"data-daemon-polygon-sts-0\"})\n* 100)\n",
       "legendFormat": "Daemon"
      },
      {
       "expr": "max without(instance,node) (\n(\n  topk(1, kubelet_volume_stats_capacity_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$namespace\", persistentvolumeclaim=\"data-indexer-polygon-sts-0\"})\n  -\n  topk(1, kubelet_volume_stats_available_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$namespace\", persistentvolumeclaim=\"data-indexer-polygon-sts-0\"})\n)\n/\ntopk(1, kubelet_volume_stats_capacity_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$namespace\", persistentvolumeclaim=\"data-indexer-polygon-sts-0\"})\n* 100)",
       "legendFormat": "Indexer"
      },
      {
       "expr": "max without(instance,node) (\n(\n  topk(1, kubelet_volume_stats_capacity_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$namespace\", persistentvolumeclaim=\"data-heimdall-polygon-sts-0\"})\n  -\n  topk(1, kubelet_volume_stats_available_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$namespace\", persistentvolumeclaim=\"data-heimdall-polygon-sts-0\"})\n)\n/\ntopk(1, kubelet_volume_stats_capacity_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$namespace\", persistentvolumeclaim=\"data-heimdall-polygon-sts-0\"})\n* 100)",
       "legendFormat": "Heimdall"
      }
     ]
    },
    {
     "title": "Average Request Duration",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 101 },
     "targets": [
      {
       "expr": "(sum(rate(label_replace(unchained_http_request_duration_seconds_sum{namespace=\"$namespace\", coinstack=\"polygon\", statusCode!=\"404\", route=~\"/api/v1/(info|gas|send|metadata).*\"}, \"endpoint\", \"$1$2\", \"route\", \"(.*?)(?:\\\\?.*|$)\")[$__rate_interval:])) by (endpoint) / sum(rate(label_replace(unchained_http_request_duration_seconds_count{namespace=\"$namespace\", coinstack=\"polygon\", statusCode!=\"404\", route=~\"/api/v1/(info|gas|send|metadata).*\"}, \"endpoint\", \"$1$2\", \"route\", \"(.*?)(?:\\\\?.*|$)\")[$__rate_interval:])) by (endpoint))",
       "legendFormat": "{{label_name}}"
      },
      {
       "expr": "(sum(rate(label_replace(unchained_http_request_duration_seconds_sum{namespace=\"$namespace\", coinstack=\"polygon\", statusCode!=\"404\", route=~\"/api/v1/account.*\"}, \"endpoint\", \"$1$2\", \"route\", \"(.*/account)(?:\\\\/.*?|\\\\?.*|$)(\\\\/.*?|$)(?:\\\\?.*|$)\")[$__rate_interval:])) by (endpoint) / sum(rate(label_replace(unchained_http_request_duration_seconds_count{namespace=\"$namespace\", coinstack=\"polygon\", statusCode!=\"404\", route=~\"/api/v1/account.*\"}, \"endpoint\", \"$1$2\", \"route\", \"(.*/account)(?:\\\\/.*?|\\\\?.*|$)(\\\\/.*?|$)(?:\\\\?.*|$)\")[$__rate_interval:])) by (endpoint))",
       "legendFormat": "{{label_name}}"
      },
      {
       "expr": "(sum(rate(label_replace(unchained_http_request_duration_seconds_sum{namespace=\"$namespace\", coinstack=\"polygon\", statusCode!=\"404\", route=~\"/api/v1/tx.*\"}, \"endpoint\", \"$1\", \"route\", \"(.*/tx).*\")[$__rate_interval:])) by (endpoint) / sum(rate(label_replace(unchained_http_request_duration_seconds_count{namespace=\"$namespace\", coinstack=\"polygon\", statusCode!=\"404\", route=~\"/api/v1/tx.*\"}, \"endpoint\", \"$1\", \"route\", \"(.*/tx).*\")[$__rate_interval:])) by (endpoint))",
       "legendFormat": "{{label_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Thorchain",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 },
   "collapsed": true,
   "panels": [
    {
     "title": "WS Connection Count",
     "type": "stat",
     "gridPos": { "h": 12, "w": 3, "x": 0, "y": 114 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(unchained_ws_client_count{coinstack=\"thorchain\", namespace=\"$namespace\"})"
      }
     ]
    },
    {
     "type": "gauge",
     "gridPos": { "h": 7, "w": 9, "x": 3, "y": 114 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(kube_deployment_status_replicas_ready{namespace=\"$namespace\", deployment=~\"thorchain-api-.*\"} / kube_deployment_status_replicas{namespace=\"$namespace\", deployment=~\"thorchain-api-.*\"}) * 100",
       "legendFormat": "API"
      },
      {
       "expr": "(kube_statefulset_status_replicas_ready{namespace=\"$namespace\", statefulset=~\"thorchain-sts\"} / kube_statefulset_replicas{namespace=\"$namespace\", statefulset=~\"thorchain-sts\"}) * 100",
       "legendFormat": "STS"
      }
     ]
    },
    {
     "title": "Request Count",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 114 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(increase(label_replace(unchained_http_request_count{namespace=\"$namespace\", coinstack=\"thorchain\", statusCode!=\"404\", route=~\"/api/v1/(info|gas|send).*\"}, \"endpoint\", \"$1\", \"route\", \"(.*?)(?:\\\\?.*|$)\")[$__rate_interval:])) by (endpoint)",
       "legendFormat": "{{endpoint}}"
      },
      {
       "expr": "sum(increase(label_replace(unchained_http_request_count{namespace=\"$namespace\", coinstack=\"thorchain\", statusCode!=\"404\", route=~\"/api/v1/(account|validators).*\"}, \"endpoint\", \"$1$3\", \"route\", \"(.*/(account|validators))(?:\\\\/.*?|\\\\?.*|$)(\\\\/.*?|$)(?:\\\\?.*|$)\")[$__rate_interval:])) by (endpoint)",
       "legendFormat": "{{endpoint}}"
      },
      {
       "expr": "sum(increase(label_replace(unchained_http_request_count{namespace=\"$namespace\", coinstack=\"thorchain\", statusCode!=\"404\", route=~\"/api/v1/tx.*\"}, \"endpoint\", \"$1\", \"route\", \"(.*/tx).*\")[$__rate_interval:])) by (endpoint)",
       "legendFormat": "{{endpoint}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 5, "w": 9, "x": 3, "y": 121 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kube_deployment_status_replicas_ready{namespace=\"$namespace\", deployment=~\"thorchain-api-.*\"}",
       "legendFormat": "Available"
      },
      {
       "expr": "kube_deployment_status_replicas{namespace=\"$namespace\", deployment=~\"thorchain-api-.*\"}",
       "legendFormat": "Total"
      },
      {
       "expr": "kube_statefulset_status_replicas_ready{namespace=\"$namespace\", statefulset=\"thorchain-sts\"}",
       "legendFormat": "Available"
      },
      {
       "expr": "kube_statefulset_replicas{namespace=\"$namespace\", statefulset=\"thorchain-sts\"}",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Volume Space Usage",
     "type": "gauge",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 126 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max without(instance,node) (\n(\n  topk(1, kubelet_volume_stats_capacity_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$namespace\", persistentvolumeclaim=~\"data-daemon-thorchain-sts-0\"})\n  -\n  topk(1, kubelet_volume_stats_available_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$namespace\", persistentvolumeclaim=\"data-daemon-thorchain-sts-0\"})\n)\n/\ntopk(1, kubelet_volume_stats_capacity_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$namespace\", persistentvolumeclaim=\"data-daemon-thorchain-sts-0\"})\n* 100)\n",
       "legendFormat": "Daemon"
      },
      {
       "expr": "max without(instance,node) (\n(\n  topk(1, kubelet_volume_stats_capacity_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$namespace\", persistentvolumeclaim=\"data-indexer-thorchain-sts-0\"})\n  -\n  topk(1, kubelet_volume_stats_available_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$namespace\", persistentvolumeclaim=\"data-indexer-thorchain-sts-0\"})\n)\n/\ntopk(1, kubelet_volume_stats_capacity_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$namespace\", persistentvolumeclaim=\"data-indexer-thorchain-sts-0\"})\n* 100)",
       "legendFormat": "Indexer"
      },
      {
       "expr": "max without(instance,node) (\n(\n  topk(1, kubelet_volume_stats_capacity_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$namespace\", persistentvolumeclaim=\"data-timescaledb-thorchain-sts-0\"})\n  -\n  topk(1, kubelet_volume_stats_available_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$namespace\", persistentvolumeclaim=\"data-timescaledb-thorchain-sts-0\"})\n)\n/\ntopk(1, kubelet_volume_stats_capacity_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$namespace\", persistentvolumeclaim=\"data-timescaledb-thorchain-sts-0\"})\n* 100)",
       "legendFormat": "Timescale DB"
      }
     ]
    },
    {
     "title": "Average Request Duration",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 126 },
     "targets": [
      {
       "expr": "(sum(rate(label_replace(unchained_http_request_duration_seconds_sum{namespace=\"$namespace\", coinstack=\"thorchain\", statusCode!=\"404\", route=~\"/api/v1/(info|gas|send).*\"}, \"endpoint\", \"$1\", \"route\", \"(.*?)(?:\\\\?.*|$)\")[$__rate_interval:])) by (endpoint) / sum(rate(label_replace(unchained_http_request_duration_seconds_count{namespace=\"$namespace\", coinstack=\"thorchain\", statusCode!=\"404\", route=~\"/api/v1/(info|gas|send).*\"}, \"endpoint\", \"$1\", \"route\", \"(.*?)(?:\\\\?.*|$)\")[$__rate_interval:])) by (endpoint))",
       "legendFormat": "{{label_name}}"
      },
      {
       "expr": "(sum(rate(label_replace(unchained_http_request_duration_seconds_sum{namespace=\"$namespace\", coinstack=\"thorchain\", statusCode!=\"404\", route=~\"/api/v1/(account|validators).*\"}, \"endpoint\", \"$1$3\", \"route\", \"(.*/(account|validators))(?:\\\\/.*?|\\\\?.*|$)(\\\\/.*?|$)(?:\\\\?.*|$)\")[$__rate_interval:])) by (endpoint) / sum(rate(label_replace(unchained_http_request_duration_seconds_count{namespace=\"$namespace\", coinstack=\"thorchain\", statusCode!=\"404\", route=~\"/api/v1/(account|validators).*\"}, \"endpoint\", \"$1$3\", \"route\", \"(.*/(account|validators))(?:\\\\/.*?|\\\\?.*|$)(\\\\/.*?|$)(?:\\\\?.*|$)\")[$__rate_interval:])) by (endpoint))",
       "legendFormat": "{{label_name}}"
      },
      {
       "expr": "(sum(rate(label_replace(unchained_http_request_duration_seconds_sum{namespace=\"$namespace\", coinstack=\"thorchain\", statusCode!=\"404\", route=~\"/api/v1/tx.*\"}, \"endpoint\", \"$1\", \"route\", \"(.*/tx).*\")[$__rate_interval:])) by (endpoint) / sum(rate(label_replace(unchained_http_request_duration_seconds_count{namespace=\"$namespace\", coinstack=\"thorchain\", statusCode!=\"404\", route=~\"/api/v1/tx.*\"}, \"endpoint\", \"$1\", \"route\", \"(.*/tx).*\")[$__rate_interval:])) by (endpoint))",
       "legendFormat": "{{label_name}}"
      }
     ]
    }
   ]
  }
 ]
}