apiVersion: v1
kind: PersistentVolume
metadata:
  finalizers:
  - kubernetes.io/pv-protection
  - external-attacher/ebs-csi-aws-com
  name: data-daemon-thorchain-sts-1-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2000Gi
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-08e46eb80cd69b1e3
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: topology.ebs.csi.aws.com/zone
          operator: In
          values:
          - us-east-2c
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ebs-csi-gp2
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-daemon-thorchain-sts-1
  namespace: unchained
  labels:
    app: unchained
    asset: thorchain
    tier: statefulservice
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2000Gi
  storageClassName: ebs-csi-gp2
  volumeName: data-daemon-thorchain-sts-1-pv
